export enum AccelcalVehiclePos {
	ACCELCAL_VEHICLE_POS_LEVEL = 1, // 
	ACCELCAL_VEHICLE_POS_LEFT = 2, // 
	ACCELCAL_VEHICLE_POS_RIGHT = 3, // 
	ACCELCAL_VEHICLE_POS_NOSEDOWN = 4, // 
	ACCELCAL_VEHICLE_POS_NOSEUP = 5, // 
	ACCELCAL_VEHICLE_POS_BACK = 6, // 
	ACCELCAL_VEHICLE_POS_SUCCESS = 16777215, // 
	ACCELCAL_VEHICLE_POS_FAILED = 16777216, // 
	ACCELCAL_VEHICLE_POS_ENUM_END = 16777217, // 
}