export enum GimbalManagerFlags {
	GIMBAL_MANAGER_FLAGS_RETRACT = 1, // Based on GIMBAL_DEVICE_FLAGS_RETRACT.
	GIMBAL_MANAGER_FLAGS_NEUTRAL = 2, // Based on GIMBAL_DEVICE_FLAGS_NEUTRAL.
	GIMBAL_MANAGER_FLAGS_ROLL_LOCK = 4, // Based on GIMBAL_DEVICE_FLAGS_ROLL_LOCK.
	GIMBAL_MANAGER_FLAGS_PITCH_LOCK = 8, // Based on GIMBAL_DEVICE_FLAGS_PITCH_LOCK.
	GIMBAL_MANAGER_FLAGS_YAW_LOCK = 16, // Based on GIMBAL_DEVICE_FLAGS_YAW_LOCK.
	GIMBAL_MANAGER_FLAGS_YAW_IN_VEHICLE_FRAME = 32, // Based on GIMBAL_DEVICE_FLAGS_YAW_IN_VEHICLE_FRAME.
	GIMBAL_MANAGER_FLAGS_YAW_IN_EARTH_FRAME = 64, // Based on GIMBAL_DEVICE_FLAGS_YAW_IN_EARTH_FRAME.
	GIMBAL_MANAGER_FLAGS_ACCEPTS_YAW_IN_EARTH_FRAME = 128, // Based on GIMBAL_DEVICE_FLAGS_ACCEPTS_YAW_IN_EARTH_FRAME.
	GIMBAL_MANAGER_FLAGS_RC_EXCLUSIVE = 256, // Based on GIMBAL_DEVICE_FLAGS_RC_EXCLUSIVE.
	GIMBAL_MANAGER_FLAGS_RC_MIXED = 512, // Based on GIMBAL_DEVICE_FLAGS_RC_MIXED.
	GIMBAL_MANAGER_FLAGS_ENUM_END = 513, // 
}