export enum GoproProtuneWhiteBalance {
	GOPRO_PROTUNE_WHITE_BALANCE_AUTO = 0, // Auto.
	GOPRO_PROTUNE_WHITE_BALANCE_3000K = 1, // 3000K.
	GOPRO_PROTUNE_WHITE_BALANCE_5500K = 2, // 5500K.
	GOPRO_PROTUNE_WHITE_BALANCE_6500K = 3, // 6500K.
	GOPRO_PROTUNE_WHITE_BALANCE_RAW = 4, // Camera Raw.
	GOPRO_PROTUNE_WHITE_BALANCE_ENUM_END = 5, // 
}