export enum GoproPhotoResolution {
	GOPRO_PHOTO_RESOLUTION_5MP_MEDIUM = 0, // 5MP Medium.
	GOPRO_PHOTO_RESOLUTION_7MP_MEDIUM = 1, // 7MP Medium.
	GOPRO_PHOTO_RESOLUTION_7MP_WIDE = 2, // 7MP Wide.
	GOPRO_PHOTO_RESOLUTION_10MP_WIDE = 3, // 10MP Wide.
	GOPRO_PHOTO_RESOLUTION_12MP_WIDE = 4, // 12MP Wide.
	GOPRO_PHOTO_RESOLUTION_ENUM_END = 5, // 
}