export enum IcarousTrackBandTypes {
	ICAROUS_TRACK_BAND_TYPE_NONE = 0, // 
	ICAROUS_TRACK_BAND_TYPE_NEAR = 1, // 
	ICAROUS_TRACK_BAND_TYPE_RECOVERY = 2, // 
	ICAROUS_TRACK_BAND_TYPES_ENUM_END = 3, // 
}