export enum MavCmdDoAuxFunctionSwitchLevel {
	MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_LOW = 0, // Switch Low.
	MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_MIDDLE = 1, // Switch Middle.
	MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_HIGH = 2, // Switch High.
	MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_ENUM_END = 3, // 
}