export enum OsdParamConfigError {
	OSD_PARAM_SUCCESS = 0, // 
	OSD_PARAM_INVALID_SCREEN = 1, // 
	OSD_PARAM_INVALID_PARAMETER_INDEX = 2, // 
	OSD_PARAM_INVALID_PARAMETER = 3, // 
	OSD_PARAM_CONFIG_ERROR_ENUM_END = 4, // 
}