export enum RoverMode {
	ROVER_MODE_MANUAL = 0, // 
	ROVER_MODE_ACRO = 1, // 
	ROVER_MODE_STEERING = 3, // 
	ROVER_MODE_HOLD = 4, // 
	ROVER_MODE_LOITER = 5, // 
	ROVER_MODE_FOLLOW = 6, // 
	ROVER_MODE_SIMPLE = 7, // 
	ROVER_MODE_AUTO = 10, // 
	ROVER_MODE_RTL = 11, // 
	ROVER_MODE_SMART_RTL = 12, // 
	ROVER_MODE_GUIDED = 15, // 
	ROVER_MODE_INITIALIZING = 16, // 
	ROVER_MODE_ENUM_END = 17, // 
}