export enum SubMode {
	SUB_MODE_STABILIZE = 0, // 
	SUB_MODE_ACRO = 1, // 
	SUB_MODE_ALT_HOLD = 2, // 
	SUB_MODE_AUTO = 3, // 
	SUB_MODE_GUIDED = 4, // 
	SUB_MODE_CIRCLE = 7, // 
	SUB_MODE_SURFACE = 9, // 
	SUB_MODE_POSHOLD = 16, // 
	SUB_MODE_MANUAL = 19, // 
	SUB_MODE_ENUM_END = 20, // 
}