export enum TrackerMode {
	TRACKER_MODE_MANUAL = 0, // 
	TRACKER_MODE_STOP = 1, // 
	TRACKER_MODE_SCAN = 2, // 
	TRACKER_MODE_SERVO_TEST = 3, // 
	TRACKER_MODE_AUTO = 10, // 
	TRACKER_MODE_INITIALIZING = 16, // 
	TRACKER_MODE_ENUM_END = 17, // 
}