export enum UavionixAdsbRfHealth {
	UAVIONIX_ADSB_RF_HEALTH_INITIALIZING = 0, // 
	UAVIONIX_ADSB_RF_HEALTH_OK = 1, // 
	UAVIONIX_ADSB_RF_HEALTH_FAIL_TX = 2, // 
	UAVIONIX_ADSB_RF_HEALTH_FAIL_RX = 16, // 
	UAVIONIX_ADSB_RF_HEALTH_ENUM_END = 17, // 
}