export enum UavionixAdsbEmergencyStatus {
	UAVIONIX_ADSB_OUT_NO_EMERGENCY = 0, // 
	UAVIONIX_ADSB_OUT_GENERAL_EMERGENCY = 1, // 
	UAVIONIX_ADSB_OUT_LIFEGUARD_EMERGENCY = 2, // 
	UAVIONIX_ADSB_OUT_MINIMUM_FUEL_EMERGENCY = 3, // 
	UAVIONIX_ADSB_OUT_NO_COMM_EMERGENCY = 4, // 
	UAVIONIX_ADSB_OUT_UNLAWFUL_INTERFERANCE_EMERGENCY = 5, // 
	UAVIONIX_ADSB_OUT_DOWNED_AIRCRAFT_EMERGENCY = 6, // 
	UAVIONIX_ADSB_OUT_RESERVED = 7, // 
	UAVIONIX_ADSB_EMERGENCY_STATUS_ENUM_END = 8, // 
}