export enum UavionixAdsbOutCfgGpsOffsetLat {
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_NO_DATA = 0, // 
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_LEFT_2M = 1, // 
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_LEFT_4M = 2, // 
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_LEFT_6M = 3, // 
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_RIGHT_0M = 4, // 
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_RIGHT_2M = 5, // 
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_RIGHT_4M = 6, // 
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_RIGHT_6M = 7, // 
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_ENUM_END = 8, // 
}