export enum UavionixAdsbOutControlState {
	UAVIONIX_ADSB_OUT_CONTROL_STATE_EXTERNAL_BARO_CROSSCHECKED = 1, // 
	UAVIONIX_ADSB_OUT_CONTROL_STATE_ON_GROUND = 4, // 
	UAVIONIX_ADSB_OUT_CONTROL_STATE_IDENT_BUTTON_ACTIVE = 8, // 
	UAVIONIX_ADSB_OUT_CONTROL_STATE_MODE_A_ENABLED = 16, // 
	UAVIONIX_ADSB_OUT_CONTROL_STATE_MODE_C_ENABLED = 32, // 
	UAVIONIX_ADSB_OUT_CONTROL_STATE_MODE_S_ENABLED = 64, // 
	UAVIONIX_ADSB_OUT_CONTROL_STATE_1090ES_TX_ENABLED = 128, // 
	UAVIONIX_ADSB_OUT_CONTROL_STATE_ENUM_END = 129, // 
}