export enum UavionixAdsbOutStatusState {
	UAVIONIX_ADSB_OUT_STATUS_STATE_ON_GROUND = 1, // 
	UAVIONIX_ADSB_OUT_STATUS_STATE_INTERROGATED_SINCE_LAST = 2, // 
	UAVIONIX_ADSB_OUT_STATUS_STATE_XBIT_ENABLED = 4, // 
	UAVIONIX_ADSB_OUT_STATUS_STATE_IDENT_ACTIVE = 8, // 
	UAVIONIX_ADSB_OUT_STATUS_STATE_MODE_A_ENABLED = 16, // 
	UAVIONIX_ADSB_OUT_STATUS_STATE_MODE_C_ENABLED = 32, // 
	UAVIONIX_ADSB_OUT_STATUS_STATE_MODE_S_ENABLED = 64, // 
	UAVIONIX_ADSB_OUT_STATUS_STATE_1090ES_TX_ENABLED = 128, // 
	UAVIONIX_ADSB_OUT_STATUS_STATE_ENUM_END = 129, // 
}