export enum UavionixAdsbOutRfSelect {
	UAVIONIX_ADSB_OUT_RF_SELECT_STANDBY = 0, // 
	UAVIONIX_ADSB_OUT_RF_SELECT_RX_ENABLED = 1, // 
	UAVIONIX_ADSB_OUT_RF_SELECT_TX_ENABLED = 2, // 
	UAVIONIX_ADSB_OUT_RF_SELECT_ENUM_END = 3, // 
}