// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccelcalVehiclePos =
  | { type: "ACCELCAL_VEHICLE_POS_LEVEL" }
  | { type: "ACCELCAL_VEHICLE_POS_LEFT" }
  | { type: "ACCELCAL_VEHICLE_POS_RIGHT" }
  | { type: "ACCELCAL_VEHICLE_POS_NOSEDOWN" }
  | { type: "ACCELCAL_VEHICLE_POS_NOSEUP" }
  | { type: "ACCELCAL_VEHICLE_POS_BACK" }
  | { type: "ACCELCAL_VEHICLE_POS_SUCCESS" }
  | { type: "ACCELCAL_VEHICLE_POS_FAILED" };
