// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActuatorConfiguration =
  | { type: "ACTUATOR_CONFIGURATION_NONE" }
  | { type: "ACTUATOR_CONFIGURATION_BEEP" }
  | { type: "ACTUATOR_CONFIGURATION_3D_MODE_ON" }
  | { type: "ACTUATOR_CONFIGURATION_3D_MODE_OFF" }
  | { type: "ACTUATOR_CONFIGURATION_SPIN_DIRECTION1" }
  | { type: "ACTUATOR_CONFIGURATION_SPIN_DIRECTION2" };
