// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ACTUATOR_OUTPUT_STATUS_DATA {
  time_usec: bigint;
  active: number;
  actuator: Array<number>;
}
