// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdsbAltitudeType } from "./AdsbAltitudeType";
import type { AdsbEmitterType } from "./AdsbEmitterType";
import type { AdsbFlags } from "./AdsbFlags";

export interface ADSB_VEHICLE_DATA {
  ICAO_address: number;
  lat: number;
  lon: number;
  altitude: number;
  heading: number;
  hor_velocity: number;
  ver_velocity: number;
  flags: AdsbFlags;
  squawk: number;
  altitude_type: AdsbAltitudeType;
  callsign: Array<number>;
  emitter_type: AdsbEmitterType;
  tslc: number;
}
