// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdsbEmitterType =
  | { type: "ADSB_EMITTER_TYPE_NO_INFO" }
  | { type: "ADSB_EMITTER_TYPE_LIGHT" }
  | { type: "ADSB_EMITTER_TYPE_SMALL" }
  | { type: "ADSB_EMITTER_TYPE_LARGE" }
  | { type: "ADSB_EMITTER_TYPE_HIGH_VORTEX_LARGE" }
  | { type: "ADSB_EMITTER_TYPE_HEAVY" }
  | { type: "ADSB_EMITTER_TYPE_HIGHLY_MANUV" }
  | { type: "ADSB_EMITTER_TYPE_ROTOCRAFT" }
  | { type: "ADSB_EMITTER_TYPE_UNASSIGNED" }
  | { type: "ADSB_EMITTER_TYPE_GLIDER" }
  | { type: "ADSB_EMITTER_TYPE_LIGHTER_AIR" }
  | { type: "ADSB_EMITTER_TYPE_PARACHUTE" }
  | { type: "ADSB_EMITTER_TYPE_ULTRA_LIGHT" }
  | { type: "ADSB_EMITTER_TYPE_UNASSIGNED2" }
  | { type: "ADSB_EMITTER_TYPE_UAV" }
  | { type: "ADSB_EMITTER_TYPE_SPACE" }
  | { type: "ADSB_EMITTER_TYPE_UNASSGINED3" }
  | { type: "ADSB_EMITTER_TYPE_EMERGENCY_SURFACE" }
  | { type: "ADSB_EMITTER_TYPE_SERVICE_SURFACE" }
  | { type: "ADSB_EMITTER_TYPE_POINT_OBSTACLE" };
