// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdsbAltitudeType =
  | { type: "ADSB_ALTITUDE_TYPE_PRESSURE_QNH" }
  | { type: "ADSB_ALTITUDE_TYPE_GEOMETRIC" };
