// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AHRS2_DATA {
  roll: number;
  pitch: number;
  yaw: number;
  altitude: number;
  lat: number;
  lng: number;
}
