// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AHRS3_DATA {
  roll: number;
  pitch: number;
  yaw: number;
  altitude: number;
  lat: number;
  lng: number;
  v1: number;
  v2: number;
  v3: number;
  v4: number;
}
