// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AIRSPEED_AUTOCAL_DATA {
  vx: number;
  vy: number;
  vz: number;
  diff_pressure: number;
  EAS2TAS: number;
  ratio: number;
  state_x: number;
  state_y: number;
  state_z: number;
  Pax: number;
  Pby: number;
  Pcz: number;
}
