// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AisFlags } from "./AisFlags";
import type { AisNavStatus } from "./AisNavStatus";
import type { AisType } from "./AisType";

export interface AIS_VESSEL_DATA {
  MMSI: number;
  lat: number;
  lon: number;
  COG: number;
  heading: number;
  velocity: number;
  dimension_bow: number;
  dimension_stern: number;
  tslc: number;
  flags: AisFlags;
  turn_rate: number;
  navigational_status: AisNavStatus;
  mavtype: AisType;
  dimension_port: number;
  dimension_starboard: number;
  callsign: Array<number>;
  name: Array<number>;
}
