// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AisNavStatus =
  | { type: "UNDER_WAY" }
  | { type: "AIS_NAV_ANCHORED" }
  | { type: "AIS_NAV_UN_COMMANDED" }
  | { type: "AIS_NAV_RESTRICTED_MANOEUVERABILITY" }
  | { type: "AIS_NAV_DRAUGHT_CONSTRAINED" }
  | { type: "AIS_NAV_MOORED" }
  | { type: "AIS_NAV_AGROUND" }
  | { type: "AIS_NAV_FISHING" }
  | { type: "AIS_NAV_SAILING" }
  | { type: "AIS_NAV_RESERVED_HSC" }
  | { type: "AIS_NAV_RESERVED_WIG" }
  | { type: "AIS_NAV_RESERVED_1" }
  | { type: "AIS_NAV_RESERVED_2" }
  | { type: "AIS_NAV_RESERVED_3" }
  | { type: "AIS_NAV_AIS_SART" }
  | { type: "AIS_NAV_UNKNOWN" };
