// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ALTITUDE_DATA {
  time_usec: bigint;
  altitude_monotonic: number;
  altitude_amsl: number;
  altitude_local: number;
  altitude_relative: number;
  altitude_terrain: number;
  bottom_clearance: number;
}
