// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AP_ADC_DATA {
  adc1: number;
  adc2: number;
  adc3: number;
  adc4: number;
  adc5: number;
  adc6: number;
}
