// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ATT_POS_MOCAP_DATA {
  time_usec: bigint;
  q: Array<number>;
  x: number;
  y: number;
  z: number;
}
