// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ATTITUDE_QUATERNION_COV_DATA {
  time_usec: bigint;
  q: Array<number>;
  rollspeed: number;
  pitchspeed: number;
  yawspeed: number;
  covariance: Array<number>;
}
