// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ATTITUDE_QUATERNION_DATA {
  time_boot_ms: number;
  q1: number;
  q2: number;
  q3: number;
  q4: number;
  rollspeed: number;
  pitchspeed: number;
  yawspeed: number;
}
