// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EstimatorStatusFlags } from "./EstimatorStatusFlags";
import type { MavLandedState } from "./MavLandedState";

export interface AUTOPILOT_STATE_FOR_GIMBAL_DEVICE_DATA {
  time_boot_us: bigint;
  q: Array<number>;
  q_estimated_delay_us: number;
  vx: number;
  vy: number;
  vz: number;
  v_estimated_delay_us: number;
  feed_forward_angular_velocity_z: number;
  estimator_status: EstimatorStatusFlags;
  target_system: number;
  target_component: number;
  landed_state: MavLandedState;
}
