// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AUTOPILOT_VERSION_REQUEST_DATA {
  target_system: number;
  target_component: number;
}
