// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutotuneAxis =
  | { type: "AUTOTUNE_AXIS_DEFAULT" }
  | { type: "AUTOTUNE_AXIS_ROLL" }
  | { type: "AUTOTUNE_AXIS_PITCH" }
  | { type: "AUTOTUNE_AXIS_YAW" };
