// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavBatteryFunction } from "./MavBatteryFunction";
import type { MavBatteryType } from "./MavBatteryType";

export interface BATTERY_STATUS_DATA {
  current_consumed: number;
  energy_consumed: number;
  temperature: number;
  voltages: Array<number>;
  current_battery: number;
  id: number;
  battery_function: MavBatteryFunction;
  mavtype: MavBatteryType;
  battery_remaining: number;
}
