// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BUTTON_CHANGE_DATA {
  time_boot_ms: number;
  last_change_ms: number;
  state: number;
}
