// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraFeedbackFlags } from "./CameraFeedbackFlags";

export interface CAMERA_FEEDBACK_DATA {
  time_usec: bigint;
  lat: number;
  lng: number;
  alt_msl: number;
  alt_rel: number;
  roll: number;
  pitch: number;
  yaw: number;
  foc_len: number;
  img_idx: number;
  target_system: number;
  cam_idx: number;
  flags: CameraFeedbackFlags;
}
