// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CameraFeedbackFlags =
  | { type: "CAMERA_FEEDBACK_PHOTO" }
  | { type: "CAMERA_FEEDBACK_VIDEO" }
  | { type: "CAMERA_FEEDBACK_BADEXPOSURE" }
  | { type: "CAMERA_FEEDBACK_CLOSEDLOOP" }
  | { type: "CAMERA_FEEDBACK_OPENLOOP" };
