// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CameraZoomType =
  | { type: "ZOOM_TYPE_STEP" }
  | { type: "ZOOM_TYPE_CONTINUOUS" }
  | { type: "ZOOM_TYPE_RANGE" }
  | { type: "ZOOM_TYPE_FOCAL_LENGTH" };
