// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraTrackingStatusFlags } from "./CameraTrackingStatusFlags";

export interface CAMERA_TRACKING_GEO_STATUS_DATA {
  lat: number;
  lon: number;
  alt: number;
  h_acc: number;
  v_acc: number;
  vel_n: number;
  vel_e: number;
  vel_d: number;
  vel_acc: number;
  dist: number;
  hdg: number;
  hdg_acc: number;
  tracking_status: CameraTrackingStatusFlags;
}
