// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CAMERA_FOV_STATUS_DATA {
  time_boot_ms: number;
  lat_camera: number;
  lon_camera: number;
  alt_camera: number;
  lat_image: number;
  lon_image: number;
  alt_image: number;
  q: Array<number>;
  hfov: number;
  vfov: number;
}
