// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraMode } from "./CameraMode";

export interface CAMERA_SETTINGS_DATA {
  time_boot_ms: number;
  mode_id: CameraMode;
}
