// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraTrackingMode } from "./CameraTrackingMode";
import type { CameraTrackingStatusFlags } from "./CameraTrackingStatusFlags";
import type { CameraTrackingTargetData } from "./CameraTrackingTargetData";

export interface CAMERA_TRACKING_IMAGE_STATUS_DATA {
  point_x: number;
  point_y: number;
  radius: number;
  rec_top_x: number;
  rec_top_y: number;
  rec_bottom_x: number;
  rec_bottom_y: number;
  tracking_status: CameraTrackingStatusFlags;
  tracking_mode: CameraTrackingMode;
  target_data: CameraTrackingTargetData;
}
