// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CameraMode =
  | { type: "CAMERA_MODE_IMAGE" }
  | { type: "CAMERA_MODE_VIDEO" }
  | { type: "CAMERA_MODE_IMAGE_SURVEY" };
