// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CAMERA_CAPTURE_STATUS_DATA {
  time_boot_ms: number;
  image_interval: number;
  recording_time_ms: number;
  available_capacity: number;
  image_status: number;
  video_status: number;
}
