// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CameraTrackingMode =
  | { type: "CAMERA_TRACKING_MODE_NONE" }
  | { type: "CAMERA_TRACKING_MODE_POINT" }
  | { type: "CAMERA_TRACKING_MODE_RECTANGLE" };
