// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CameraStatusTypes =
  | { type: "CAMERA_STATUS_TYPE_HEARTBEAT" }
  | { type: "CAMERA_STATUS_TYPE_TRIGGER" }
  | { type: "CAMERA_STATUS_TYPE_DISCONNECT" }
  | { type: "CAMERA_STATUS_TYPE_ERROR" }
  | { type: "CAMERA_STATUS_TYPE_LOWBATT" }
  | { type: "CAMERA_STATUS_TYPE_LOWSTORE" }
  | { type: "CAMERA_STATUS_TYPE_LOWSTOREV" };
