// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CameraTrackingStatusFlags =
  | { type: "CAMERA_TRACKING_STATUS_FLAGS_IDLE" }
  | { type: "CAMERA_TRACKING_STATUS_FLAGS_ACTIVE" }
  | { type: "CAMERA_TRACKING_STATUS_FLAGS_ERROR" };
