// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CameraTrackingTargetData =
  | { type: "CAMERA_TRACKING_TARGET_DATA_NONE" }
  | { type: "CAMERA_TRACKING_TARGET_DATA_EMBEDDED" }
  | { type: "CAMERA_TRACKING_TARGET_DATA_RENDERED" }
  | { type: "CAMERA_TRACKING_TARGET_DATA_IN_STATUS" };
