// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CAMERA_IMAGE_CAPTURED_DATA {
  time_utc: bigint;
  time_boot_ms: number;
  lat: number;
  lon: number;
  alt: number;
  relative_alt: number;
  q: Array<number>;
  image_index: number;
  camera_id: number;
  capture_result: number;
  file_url: Array<number>;
}
