// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraCapFlags } from "./CameraCapFlags";

export interface CAMERA_INFORMATION_DATA {
  time_boot_ms: number;
  firmware_version: number;
  focal_length: number;
  sensor_size_h: number;
  sensor_size_v: number;
  flags: CameraCapFlags;
  resolution_h: number;
  resolution_v: number;
  cam_definition_version: number;
  vendor_name: Array<number>;
  model_name: Array<number>;
  lens_id: number;
  cam_definition_uri: Array<number>;
}
