// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraStatusTypes } from "./CameraStatusTypes";

export interface CAMERA_STATUS_DATA {
  time_usec: bigint;
  p1: number;
  p2: number;
  p3: number;
  p4: number;
  img_idx: number;
  target_system: number;
  cam_idx: number;
  event_id: CameraStatusTypes;
}
