// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanFilterOp } from "./CanFilterOp";

export interface CAN_FILTER_MODIFY_DATA {
  ids: Array<number>;
  target_system: number;
  target_component: number;
  bus: number;
  operation: CanFilterOp;
  num_ids: number;
}
