// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CAN_FRAME_DATA {
  id: number;
  target_system: number;
  target_component: number;
  bus: number;
  len: number;
  data: Array<number>;
}
