// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CanFilterOp =
  | { type: "CAN_FILTER_REPLACE" }
  | { type: "CAN_FILTER_ADD" }
  | { type: "CAN_FILTER_REMOVE" };
