// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellularConfigResponse } from "./CellularConfigResponse";

export interface CELLULAR_CONFIG_DATA {
  enable_lte: number;
  enable_pin: number;
  pin: Array<number>;
  new_pin: Array<number>;
  apn: Array<number>;
  puk: Array<number>;
  roaming: number;
  response: CellularConfigResponse;
}
