// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CellularStatusFlag =
  | { type: "CELLULAR_STATUS_FLAG_UNKNOWN" }
  | { type: "CELLULAR_STATUS_FLAG_FAILED" }
  | { type: "CELLULAR_STATUS_FLAG_INITIALIZING" }
  | { type: "CELLULAR_STATUS_FLAG_LOCKED" }
  | { type: "CELLULAR_STATUS_FLAG_DISABLED" }
  | { type: "CELLULAR_STATUS_FLAG_DISABLING" }
  | { type: "CELLULAR_STATUS_FLAG_ENABLING" }
  | { type: "CELLULAR_STATUS_FLAG_ENABLED" }
  | { type: "CELLULAR_STATUS_FLAG_SEARCHING" }
  | { type: "CELLULAR_STATUS_FLAG_REGISTERED" }
  | { type: "CELLULAR_STATUS_FLAG_DISCONNECTING" }
  | { type: "CELLULAR_STATUS_FLAG_CONNECTING" }
  | { type: "CELLULAR_STATUS_FLAG_CONNECTED" };
