// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CellularNetworkRadioType =
  | { type: "CELLULAR_NETWORK_RADIO_TYPE_NONE" }
  | { type: "CELLULAR_NETWORK_RADIO_TYPE_GSM" }
  | { type: "CELLULAR_NETWORK_RADIO_TYPE_CDMA" }
  | { type: "CELLULAR_NETWORK_RADIO_TYPE_WCDMA" }
  | { type: "CELLULAR_NETWORK_RADIO_TYPE_LTE" };
