// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CellularConfigResponse =
  | { type: "CELLULAR_CONFIG_RESPONSE_ACCEPTED" }
  | { type: "CELLULAR_CONFIG_RESPONSE_APN_ERROR" }
  | { type: "CELLULAR_CONFIG_RESPONSE_PIN_ERROR" }
  | { type: "CELLULAR_CONFIG_RESPONSE_REJECTED" }
  | { type: "CELLULAR_CONFIG_BLOCKED_PUK_REQUIRED" };
