// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellularNetworkFailedReason } from "./CellularNetworkFailedReason";
import type { CellularNetworkRadioType } from "./CellularNetworkRadioType";
import type { CellularStatusFlag } from "./CellularStatusFlag";

export interface CELLULAR_STATUS_DATA {
  mcc: number;
  mnc: number;
  lac: number;
  status: CellularStatusFlag;
  failure_reason: CellularNetworkFailedReason;
  mavtype: CellularNetworkRadioType;
  quality: number;
}
