// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CellularNetworkFailedReason =
  | { type: "CELLULAR_NETWORK_FAILED_REASON_NONE" }
  | { type: "CELLULAR_NETWORK_FAILED_REASON_UNKNOWN" }
  | { type: "CELLULAR_NETWORK_FAILED_REASON_SIM_MISSING" }
  | { type: "CELLULAR_NETWORK_FAILED_REASON_SIM_ERROR" };
