// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CHANGE_OPERATOR_CONTROL_ACK_DATA {
  gcs_system_id: number;
  control_request: number;
  ack: number;
}
