// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CHANGE_OPERATOR_CONTROL_DATA {
  target_system: number;
  control_request: number;
  version: number;
  passkey: Array<number>;
}
