// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavCollisionAction } from "./MavCollisionAction";
import type { MavCollisionSrc } from "./MavCollisionSrc";
import type { MavCollisionThreatLevel } from "./MavCollisionThreatLevel";

export interface COLLISION_DATA {
  id: number;
  time_to_minimum_delta: number;
  altitude_minimum_delta: number;
  horizontal_minimum_delta: number;
  src: MavCollisionSrc;
  action: MavCollisionAction;
  threat_level: MavCollisionThreatLevel;
}
