// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavCmd } from "./MavCmd";
import type { MavResult } from "./MavResult";

export interface COMMAND_ACK_DATA {
  command: MavCmd;
  result: MavResult;
}
