// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavCmd } from "./MavCmd";

export interface COMMAND_LONG_DATA {
  param1: number;
  param2: number;
  param3: number;
  param4: number;
  param5: number;
  param6: number;
  param7: number;
  command: MavCmd;
  target_system: number;
  target_component: number;
  confirmation: number;
}
