// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavCmd } from "./MavCmd";

export interface COMMAND_CANCEL_DATA {
  command: MavCmd;
  target_system: number;
  target_component: number;
}
