// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompMetadataType =
  | { type: "COMP_METADATA_TYPE_GENERAL" }
  | { type: "COMP_METADATA_TYPE_PARAMETER" }
  | { type: "COMP_METADATA_TYPE_COMMANDS" }
  | { type: "COMP_METADATA_TYPE_PERIPHERALS" }
  | { type: "COMP_METADATA_TYPE_EVENTS" }
  | { type: "COMP_METADATA_TYPE_ACTUATORS" };
