// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface COMPONENT_METADATA_DATA {
  time_boot_ms: number;
  file_crc: number;
  uri: Array<number>;
}
