// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface COMPONENT_INFORMATION_DATA {
  time_boot_ms: number;
  general_metadata_file_crc: number;
  peripherals_metadata_file_crc: number;
  general_metadata_uri: Array<number>;
  peripherals_metadata_uri: Array<number>;
}
