// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CopterMode =
  | { type: "COPTER_MODE_STABILIZE" }
  | { type: "COPTER_MODE_ACRO" }
  | { type: "COPTER_MODE_ALT_HOLD" }
  | { type: "COPTER_MODE_AUTO" }
  | { type: "COPTER_MODE_GUIDED" }
  | { type: "COPTER_MODE_LOITER" }
  | { type: "COPTER_MODE_RTL" }
  | { type: "COPTER_MODE_CIRCLE" }
  | { type: "COPTER_MODE_LAND" }
  | { type: "COPTER_MODE_DRIFT" }
  | { type: "COPTER_MODE_SPORT" }
  | { type: "COPTER_MODE_FLIP" }
  | { type: "COPTER_MODE_AUTOTUNE" }
  | { type: "COPTER_MODE_POSHOLD" }
  | { type: "COPTER_MODE_BRAKE" }
  | { type: "COPTER_MODE_THROW" }
  | { type: "COPTER_MODE_AVOID_ADSB" }
  | { type: "COPTER_MODE_GUIDED_NOGPS" }
  | { type: "COPTER_MODE_SMART_RTL" }
  | { type: "COPTER_MODE_FLOWHOLD" }
  | { type: "COPTER_MODE_FOLLOW" }
  | { type: "COPTER_MODE_ZIGZAG" }
  | { type: "COPTER_MODE_SYSTEMID" }
  | { type: "COPTER_MODE_AUTOROTATE" }
  | { type: "COPTER_MODE_AUTO_RTL" };
