// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CUBEPILOT_FIRMWARE_UPDATE_START_DATA {
  size: number;
  crc: number;
  target_system: number;
  target_component: number;
}
