// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavEventCurrentSequenceFlags } from "./MavEventCurrentSequenceFlags";

export interface CURRENT_EVENT_SEQUENCE_DATA {
  sequence: number;
  flags: MavEventCurrentSequenceFlags;
}
