// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DATA_STREAM_DATA {
  message_rate: number;
  stream_id: number;
  on_off: number;
}
