// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DATA16_DATA {
  mavtype: number;
  len: number;
  data: Array<number>;
}
