// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavlinkDataStreamType } from "./MavlinkDataStreamType";

export interface DATA_TRANSMISSION_HANDSHAKE_DATA {
  size: number;
  width: number;
  height: number;
  packets: number;
  mavtype: MavlinkDataStreamType;
  payload: number;
  jpg_quality: number;
}
