// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DEBUG_FLOAT_ARRAY_DATA {
  time_usec: bigint;
  array_id: number;
  name: Array<number>;
}
