// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DEBUG_VECT_DATA {
  time_usec: bigint;
  x: number;
  y: number;
  z: number;
  name: Array<number>;
}
