// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeepstallStage =
  | { type: "DEEPSTALL_STAGE_FLY_TO_LANDING" }
  | { type: "DEEPSTALL_STAGE_ESTIMATE_WIND" }
  | { type: "DEEPSTALL_STAGE_WAIT_FOR_BREAKOUT" }
  | { type: "DEEPSTALL_STAGE_FLY_TO_ARC" }
  | { type: "DEEPSTALL_STAGE_ARC" }
  | { type: "DEEPSTALL_STAGE_APPROACH" }
  | { type: "DEEPSTALL_STAGE_LAND" };
