// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DEVICE_OP_READ_REPLY_DATA {
  request_id: number;
  result: number;
  regstart: number;
  count: number;
  data: Array<number>;
}
