// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceOpBustype =
  | { type: "DEVICE_OP_BUSTYPE_I2C" }
  | { type: "DEVICE_OP_BUSTYPE_SPI" };
