// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceOpBustype } from "./DeviceOpBustype";

export interface DEVICE_OP_READ_DATA {
  request_id: number;
  target_system: number;
  target_component: number;
  bustype: DeviceOpBustype;
  bus: number;
  address: number;
  busname: Array<number>;
  regstart: number;
  count: number;
}
