// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DIGICAM_CONTROL_DATA {
  extra_value: number;
  target_system: number;
  target_component: number;
  session: number;
  zoom_pos: number;
  zoom_step: number;
  focus_lock: number;
  shot: number;
  command_id: number;
  extra_param: number;
}
