// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DIGICAM_CONFIGURE_DATA {
  extra_value: number;
  shutter_speed: number;
  target_system: number;
  target_component: number;
  mode: number;
  aperture: number;
  iso: number;
  exposure_type: number;
  command_id: number;
  engine_cut_off: number;
  extra_param: number;
}
