// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavDistanceSensor } from "./MavDistanceSensor";
import type { MavSensorOrientation } from "./MavSensorOrientation";

export interface DISTANCE_SENSOR_DATA {
  time_boot_ms: number;
  min_distance: number;
  max_distance: number;
  current_distance: number;
  mavtype: MavDistanceSensor;
  id: number;
  orientation: MavSensorOrientation;
  covariance: number;
}
