// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EFI_STATUS_DATA {
  ecu_index: number;
  rpm: number;
  fuel_consumed: number;
  fuel_flow: number;
  engine_load: number;
  throttle_position: number;
  spark_dwell_time: number;
  barometric_pressure: number;
  intake_manifold_pressure: number;
  intake_manifold_temperature: number;
  cylinder_head_temperature: number;
  ignition_timing: number;
  injection_time: number;
  exhaust_gas_temperature: number;
  throttle_out: number;
  pt_compensation: number;
  health: number;
}
