// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EkfStatusFlags } from "./EkfStatusFlags";

export interface EKF_STATUS_REPORT_DATA {
  velocity_variance: number;
  pos_horiz_variance: number;
  pos_vert_variance: number;
  compass_variance: number;
  terrain_alt_variance: number;
  flags: EkfStatusFlags;
}
