// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ESC_STATUS_DATA {
  time_usec: bigint;
  rpm: Array<number>;
  voltage: Array<number>;
  current: Array<number>;
  index: number;
}
