// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ESC_TELEMETRY_1_TO_4_DATA {
  voltage: Array<number>;
  current: Array<number>;
  totalcurrent: Array<number>;
  rpm: Array<number>;
  count: Array<number>;
  temperature: Array<number>;
}
