// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EscConnectionType } from "./EscConnectionType";

export interface ESC_INFO_DATA {
  time_usec: bigint;
  error_count: Array<number>;
  counter: number;
  failure_flags: Array<number>;
  temperature: Array<number>;
  index: number;
  count: number;
  connection_type: EscConnectionType;
  info: number;
}
