// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EscConnectionType =
  | { type: "ESC_CONNECTION_TYPE_PPM" }
  | { type: "ESC_CONNECTION_TYPE_SERIAL" }
  | { type: "ESC_CONNECTION_TYPE_ONESHOT" }
  | { type: "ESC_CONNECTION_TYPE_I2C" }
  | { type: "ESC_CONNECTION_TYPE_CAN" }
  | { type: "ESC_CONNECTION_TYPE_DSHOT" };
