// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EstimatorStatusFlags } from "./EstimatorStatusFlags";

export interface ESTIMATOR_STATUS_DATA {
  time_usec: bigint;
  vel_ratio: number;
  pos_horiz_ratio: number;
  pos_vert_ratio: number;
  mag_ratio: number;
  hagl_ratio: number;
  tas_ratio: number;
  pos_horiz_accuracy: number;
  pos_vert_accuracy: number;
  flags: EstimatorStatusFlags;
}
