// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EVENT_DATA {
  id: number;
  event_time_boot_ms: number;
  sequence: number;
  destination_component: number;
  destination_system: number;
  log_levels: number;
  arguments: Array<number>;
}
