// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavLandedState } from "./MavLandedState";
import type { MavVtolState } from "./MavVtolState";

export interface EXTENDED_SYS_STATE_DATA {
  vtol_state: MavVtolState;
  landed_state: MavLandedState;
}
