// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FailureType =
  | { type: "FAILURE_TYPE_OK" }
  | { type: "FAILURE_TYPE_OFF" }
  | { type: "FAILURE_TYPE_STUCK" }
  | { type: "FAILURE_TYPE_GARBAGE" }
  | { type: "FAILURE_TYPE_WRONG" }
  | { type: "FAILURE_TYPE_SLOW" }
  | { type: "FAILURE_TYPE_DELAYED" }
  | { type: "FAILURE_TYPE_INTERMITTENT" };
