// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FailureUnit =
  | { type: "FAILURE_UNIT_SENSOR_GYRO" }
  | { type: "FAILURE_UNIT_SENSOR_ACCEL" }
  | { type: "FAILURE_UNIT_SENSOR_MAG" }
  | { type: "FAILURE_UNIT_SENSOR_BARO" }
  | { type: "FAILURE_UNIT_SENSOR_GPS" }
  | { type: "FAILURE_UNIT_SENSOR_OPTICAL_FLOW" }
  | { type: "FAILURE_UNIT_SENSOR_VIO" }
  | { type: "FAILURE_UNIT_SENSOR_DISTANCE_SENSOR" }
  | { type: "FAILURE_UNIT_SENSOR_AIRSPEED" }
  | { type: "FAILURE_UNIT_SYSTEM_BATTERY" }
  | { type: "FAILURE_UNIT_SYSTEM_MOTOR" }
  | { type: "FAILURE_UNIT_SYSTEM_SERVO" }
  | { type: "FAILURE_UNIT_SYSTEM_AVOIDANCE" }
  | { type: "FAILURE_UNIT_SYSTEM_RC_SIGNAL" }
  | { type: "FAILURE_UNIT_SYSTEM_MAVLINK_SIGNAL" };
