// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FenceBreach =
  | { type: "FENCE_BREACH_NONE" }
  | { type: "FENCE_BREACH_MINALT" }
  | { type: "FENCE_BREACH_MAXALT" }
  | { type: "FENCE_BREACH_BOUNDARY" };
