// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FENCE_POINT_DATA {
  lat: number;
  lng: number;
  target_system: number;
  target_component: number;
  idx: number;
  count: number;
}
