// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FenceAction =
  | { type: "FENCE_ACTION_NONE" }
  | { type: "FENCE_ACTION_GUIDED" }
  | { type: "FENCE_ACTION_REPORT" }
  | { type: "FENCE_ACTION_GUIDED_THR_PASS" }
  | { type: "FENCE_ACTION_RTL" }
  | { type: "FENCE_ACTION_HOLD" }
  | { type: "FENCE_ACTION_TERMINATE" }
  | { type: "FENCE_ACTION_LAND" };
