// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FenceBreach } from "./FenceBreach";

export interface FENCE_STATUS_DATA {
  breach_time: number;
  breach_count: number;
  breach_status: number;
  breach_type: FenceBreach;
}
