// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FenceMitigate =
  | { type: "FENCE_MITIGATE_UNKNOWN" }
  | { type: "FENCE_MITIGATE_NONE" }
  | { type: "FENCE_MITIGATE_VEL_LIMIT" };
