// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FirmwareVersionType =
  | { type: "FIRMWARE_VERSION_TYPE_DEV" }
  | { type: "FIRMWARE_VERSION_TYPE_ALPHA" }
  | { type: "FIRMWARE_VERSION_TYPE_BETA" }
  | { type: "FIRMWARE_VERSION_TYPE_RC" }
  | { type: "FIRMWARE_VERSION_TYPE_OFFICIAL" };
