// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FLIGHT_INFORMATION_DATA {
  arming_time_utc: bigint;
  takeoff_time_utc: bigint;
  flight_uuid: bigint;
  time_boot_ms: number;
}
