// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FOLLOW_TARGET_DATA {
  timestamp: bigint;
  custom_state: bigint;
  lat: number;
  lon: number;
  alt: number;
  vel: Array<number>;
  acc: Array<number>;
  attitude_q: Array<number>;
  rates: Array<number>;
  position_cov: Array<number>;
  est_capabilities: number;
}
