// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GimbalDeviceCapFlags } from "./GimbalDeviceCapFlags";

export interface GIMBAL_DEVICE_INFORMATION_DATA {
  uid: bigint;
  time_boot_ms: number;
  firmware_version: number;
  hardware_version: number;
  roll_min: number;
  roll_max: number;
  pitch_min: number;
  pitch_max: number;
  yaw_min: number;
  yaw_max: number;
  cap_flags: GimbalDeviceCapFlags;
  custom_cap_flags: number;
  vendor_name: Array<number>;
  model_name: Array<number>;
  custom_name: Array<number>;
}
