// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GimbalAxis =
  | { type: "GIMBAL_AXIS_YAW" }
  | { type: "GIMBAL_AXIS_PITCH" }
  | { type: "GIMBAL_AXIS_ROLL" };
