// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GIMBAL_CONTROL_DATA {
  demanded_rate_x: number;
  demanded_rate_y: number;
  demanded_rate_z: number;
  target_system: number;
  target_component: number;
}
