// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GimbalAxisCalibrationStatus =
  | { type: "GIMBAL_AXIS_CALIBRATION_STATUS_IN_PROGRESS" }
  | { type: "GIMBAL_AXIS_CALIBRATION_STATUS_SUCCEEDED" }
  | { type: "GIMBAL_AXIS_CALIBRATION_STATUS_FAILED" };
