// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GimbalManagerFlags =
  | { type: "GIMBAL_MANAGER_FLAGS_RETRACT" }
  | { type: "GIMBAL_MANAGER_FLAGS_NEUTRAL" }
  | { type: "GIMBAL_MANAGER_FLAGS_ROLL_LOCK" }
  | { type: "GIMBAL_MANAGER_FLAGS_PITCH_LOCK" }
  | { type: "GIMBAL_MANAGER_FLAGS_YAW_LOCK" }
  | { type: "GIMBAL_MANAGER_FLAGS_YAW_IN_VEHICLE_FRAME" }
  | { type: "GIMBAL_MANAGER_FLAGS_YAW_IN_EARTH_FRAME" }
  | { type: "GIMBAL_MANAGER_FLAGS_ACCEPTS_YAW_IN_EARTH_FRAME" }
  | { type: "GIMBAL_MANAGER_FLAGS_RC_EXCLUSIVE" }
  | { type: "GIMBAL_MANAGER_FLAGS_RC_MIXED" };
