// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GIMBAL_REPORT_DATA {
  delta_time: number;
  delta_angle_x: number;
  delta_angle_y: number;
  delta_angle_z: number;
  delta_velocity_x: number;
  delta_velocity_y: number;
  delta_velocity_z: number;
  joint_roll: number;
  joint_el: number;
  joint_az: number;
  target_system: number;
  target_component: number;
}
