// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GimbalDeviceFlags } from "./GimbalDeviceFlags";

export interface GIMBAL_DEVICE_SET_ATTITUDE_DATA {
  q: Array<number>;
  angular_velocity_x: number;
  angular_velocity_y: number;
  angular_velocity_z: number;
  flags: GimbalDeviceFlags;
  target_system: number;
  target_component: number;
}
