// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GimbalManagerFlags } from "./GimbalManagerFlags";

export interface GIMBAL_MANAGER_SET_MANUAL_CONTROL_DATA {
  flags: GimbalManagerFlags;
  pitch: number;
  yaw: number;
  pitch_rate: number;
  yaw_rate: number;
  target_system: number;
  target_component: number;
  gimbal_device_id: number;
}
