// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GimbalManagerCapFlags } from "./GimbalManagerCapFlags";

export interface GIMBAL_MANAGER_INFORMATION_DATA {
  time_boot_ms: number;
  cap_flags: GimbalManagerCapFlags;
  roll_min: number;
  roll_max: number;
  pitch_min: number;
  pitch_max: number;
  yaw_min: number;
  yaw_max: number;
  gimbal_device_id: number;
}
