// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GimbalAxisCalibrationRequired =
  | { type: "GIMBAL_AXIS_CALIBRATION_REQUIRED_UNKNOWN" }
  | { type: "GIMBAL_AXIS_CALIBRATION_REQUIRED_TRUE" }
  | { type: "GIMBAL_AXIS_CALIBRATION_REQUIRED_FALSE" };
