// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GIMBAL_TORQUE_CMD_REPORT_DATA {
  rl_torque_cmd: number;
  el_torque_cmd: number;
  az_torque_cmd: number;
  target_system: number;
  target_component: number;
}
