// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavEstimatorType } from "./MavEstimatorType";

export interface GLOBAL_POSITION_INT_COV_DATA {
  time_usec: bigint;
  lat: number;
  lon: number;
  alt: number;
  relative_alt: number;
  vx: number;
  vy: number;
  vz: number;
  covariance: Array<number>;
  estimator_type: MavEstimatorType;
}
