// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproFieldOfView =
  | { type: "GOPRO_FIELD_OF_VIEW_WIDE" }
  | { type: "GOPRO_FIELD_OF_VIEW_MEDIUM" }
  | { type: "GOPRO_FIELD_OF_VIEW_NARROW" };
