// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproHeartbeatStatus =
  | { type: "GOPRO_HEARTBEAT_STATUS_DISCONNECTED" }
  | { type: "GOPRO_HEARTBEAT_STATUS_INCOMPATIBLE" }
  | { type: "GOPRO_HEARTBEAT_STATUS_CONNECTED" }
  | { type: "GOPRO_HEARTBEAT_STATUS_ERROR" };
