// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproCommand =
  | { type: "GOPRO_COMMAND_POWER" }
  | { type: "GOPRO_COMMAND_CAPTURE_MODE" }
  | { type: "GOPRO_COMMAND_SHUTTER" }
  | { type: "GOPRO_COMMAND_BATTERY" }
  | { type: "GOPRO_COMMAND_MODEL" }
  | { type: "GOPRO_COMMAND_VIDEO_SETTINGS" }
  | { type: "GOPRO_COMMAND_LOW_LIGHT" }
  | { type: "GOPRO_COMMAND_PHOTO_RESOLUTION" }
  | { type: "GOPRO_COMMAND_PHOTO_BURST_RATE" }
  | { type: "GOPRO_COMMAND_PROTUNE" }
  | { type: "GOPRO_COMMAND_PROTUNE_WHITE_BALANCE" }
  | { type: "GOPRO_COMMAND_PROTUNE_COLOUR" }
  | { type: "GOPRO_COMMAND_PROTUNE_GAIN" }
  | { type: "GOPRO_COMMAND_PROTUNE_SHARPNESS" }
  | { type: "GOPRO_COMMAND_PROTUNE_EXPOSURE" }
  | { type: "GOPRO_COMMAND_TIME" }
  | { type: "GOPRO_COMMAND_CHARGING" };
