// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproProtuneExposure =
  | { type: "GOPRO_PROTUNE_EXPOSURE_NEG_5_0" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_NEG_4_5" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_NEG_4_0" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_NEG_3_5" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_NEG_3_0" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_NEG_2_5" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_NEG_2_0" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_NEG_1_5" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_NEG_1_0" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_NEG_0_5" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_ZERO" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_POS_0_5" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_POS_1_0" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_POS_1_5" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_POS_2_0" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_POS_2_5" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_POS_3_0" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_POS_3_5" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_POS_4_0" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_POS_4_5" }
  | { type: "GOPRO_PROTUNE_EXPOSURE_POS_5_0" };
