// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproCaptureMode =
  | { type: "GOPRO_CAPTURE_MODE_VIDEO" }
  | { type: "GOPRO_CAPTURE_MODE_PHOTO" }
  | { type: "GOPRO_CAPTURE_MODE_BURST" }
  | { type: "GOPRO_CAPTURE_MODE_TIME_LAPSE" }
  | { type: "GOPRO_CAPTURE_MODE_MULTI_SHOT" }
  | { type: "GOPRO_CAPTURE_MODE_PLAYBACK" }
  | { type: "GOPRO_CAPTURE_MODE_SETUP" }
  | { type: "GOPRO_CAPTURE_MODE_UNKNOWN" };
