// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproProtuneWhiteBalance =
  | { type: "GOPRO_PROTUNE_WHITE_BALANCE_AUTO" }
  | { type: "GOPRO_PROTUNE_WHITE_BALANCE_3000K" }
  | { type: "GOPRO_PROTUNE_WHITE_BALANCE_5500K" }
  | { type: "GOPRO_PROTUNE_WHITE_BALANCE_6500K" }
  | { type: "GOPRO_PROTUNE_WHITE_BALANCE_RAW" };
