// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproRequestStatus =
  | { type: "GOPRO_REQUEST_SUCCESS" }
  | { type: "GOPRO_REQUEST_FAILED" };
