// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproProtuneSharpness =
  | { type: "GOPRO_PROTUNE_SHARPNESS_LOW" }
  | { type: "GOPRO_PROTUNE_SHARPNESS_MEDIUM" }
  | { type: "GOPRO_PROTUNE_SHARPNESS_HIGH" };
