// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproResolution =
  | { type: "GOPRO_RESOLUTION_480p" }
  | { type: "GOPRO_RESOLUTION_720p" }
  | { type: "GOPRO_RESOLUTION_960p" }
  | { type: "GOPRO_RESOLUTION_1080p" }
  | { type: "GOPRO_RESOLUTION_1440p" }
  | { type: "GOPRO_RESOLUTION_2_7k_17_9" }
  | { type: "GOPRO_RESOLUTION_2_7k_16_9" }
  | { type: "GOPRO_RESOLUTION_2_7k_4_3" }
  | { type: "GOPRO_RESOLUTION_4k_16_9" }
  | { type: "GOPRO_RESOLUTION_4k_17_9" }
  | { type: "GOPRO_RESOLUTION_720p_SUPERVIEW" }
  | { type: "GOPRO_RESOLUTION_1080p_SUPERVIEW" }
  | { type: "GOPRO_RESOLUTION_2_7k_SUPERVIEW" }
  | { type: "GOPRO_RESOLUTION_4k_SUPERVIEW" };
