// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproFrameRate =
  | { type: "GOPRO_FRAME_RATE_12" }
  | { type: "GOPRO_FRAME_RATE_15" }
  | { type: "GOPRO_FRAME_RATE_24" }
  | { type: "GOPRO_FRAME_RATE_25" }
  | { type: "GOPRO_FRAME_RATE_30" }
  | { type: "GOPRO_FRAME_RATE_48" }
  | { type: "GOPRO_FRAME_RATE_50" }
  | { type: "GOPRO_FRAME_RATE_60" }
  | { type: "GOPRO_FRAME_RATE_80" }
  | { type: "GOPRO_FRAME_RATE_90" }
  | { type: "GOPRO_FRAME_RATE_100" }
  | { type: "GOPRO_FRAME_RATE_120" }
  | { type: "GOPRO_FRAME_RATE_240" }
  | { type: "GOPRO_FRAME_RATE_12_5" };
