// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproPhotoResolution =
  | { type: "GOPRO_PHOTO_RESOLUTION_5MP_MEDIUM" }
  | { type: "GOPRO_PHOTO_RESOLUTION_7MP_MEDIUM" }
  | { type: "GOPRO_PHOTO_RESOLUTION_7MP_WIDE" }
  | { type: "GOPRO_PHOTO_RESOLUTION_10MP_WIDE" }
  | { type: "GOPRO_PHOTO_RESOLUTION_12MP_WIDE" };
