// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproModel =
  | { type: "GOPRO_MODEL_UNKNOWN" }
  | { type: "GOPRO_MODEL_HERO_3_PLUS_SILVER" }
  | { type: "GOPRO_MODEL_HERO_3_PLUS_BLACK" }
  | { type: "GOPRO_MODEL_HERO_4_SILVER" }
  | { type: "GOPRO_MODEL_HERO_4_BLACK" };
