// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproBurstRate =
  | { type: "GOPRO_BURST_RATE_3_IN_1_SECOND" }
  | { type: "GOPRO_BURST_RATE_5_IN_1_SECOND" }
  | { type: "GOPRO_BURST_RATE_10_IN_1_SECOND" }
  | { type: "GOPRO_BURST_RATE_10_IN_2_SECOND" }
  | { type: "GOPRO_BURST_RATE_10_IN_3_SECOND" }
  | { type: "GOPRO_BURST_RATE_30_IN_1_SECOND" }
  | { type: "GOPRO_BURST_RATE_30_IN_2_SECOND" }
  | { type: "GOPRO_BURST_RATE_30_IN_3_SECOND" }
  | { type: "GOPRO_BURST_RATE_30_IN_6_SECOND" };
