// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproProtuneColour =
  | { type: "GOPRO_PROTUNE_COLOUR_STANDARD" }
  | { type: "GOPRO_PROTUNE_COLOUR_NEUTRAL" };
