// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoproProtuneGain =
  | { type: "GOPRO_PROTUNE_GAIN_400" }
  | { type: "GOPRO_PROTUNE_GAIN_800" }
  | { type: "GOPRO_PROTUNE_GAIN_1600" }
  | { type: "GOPRO_PROTUNE_GAIN_3200" }
  | { type: "GOPRO_PROTUNE_GAIN_6400" };
