// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoproCaptureMode } from "./GoproCaptureMode";
import type { GoproHeartbeatFlags } from "./GoproHeartbeatFlags";
import type { GoproHeartbeatStatus } from "./GoproHeartbeatStatus";

export interface GOPRO_HEARTBEAT_DATA {
  status: GoproHeartbeatStatus;
  capture_mode: GoproCaptureMode;
  flags: GoproHeartbeatFlags;
}
