// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoproCommand } from "./GoproCommand";
import type { GoproRequestStatus } from "./GoproRequestStatus";

export interface GOPRO_SET_RESPONSE_DATA {
  cmd_id: GoproCommand;
  status: GoproRequestStatus;
}
