// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RtkBaselineCoordinateSystem } from "./RtkBaselineCoordinateSystem";

export interface GPS2_RTK_DATA {
  time_last_baseline_ms: number;
  tow: number;
  baseline_a_mm: number;
  baseline_b_mm: number;
  baseline_c_mm: number;
  accuracy: number;
  iar_num_hypotheses: number;
  wn: number;
  rtk_receiver_id: number;
  rtk_health: number;
  rtk_rate: number;
  nsats: number;
  baseline_coords_type: RtkBaselineCoordinateSystem;
}
