// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GPS_STATUS_DATA {
  satellites_visible: number;
  satellite_prn: Array<number>;
  satellite_used: Array<number>;
  satellite_elevation: Array<number>;
  satellite_azimuth: Array<number>;
  satellite_snr: Array<number>;
}
