// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GPS_INJECT_DATA_DATA {
  target_system: number;
  target_component: number;
  len: number;
  data: Array<number>;
}
