// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GPS_GLOBAL_ORIGIN_DATA {
  latitude: number;
  longitude: number;
  altitude: number;
}
