// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpsFixType } from "./GpsFixType";

export interface GPS_RAW_INT_DATA {
  time_usec: bigint;
  lat: number;
  lon: number;
  alt: number;
  eph: number;
  epv: number;
  vel: number;
  cog: number;
  fix_type: GpsFixType;
  satellites_visible: number;
}
