// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GpsFixType =
  | { type: "GPS_FIX_TYPE_NO_GPS" }
  | { type: "GPS_FIX_TYPE_NO_FIX" }
  | { type: "GPS_FIX_TYPE_2D_FIX" }
  | { type: "GPS_FIX_TYPE_3D_FIX" }
  | { type: "GPS_FIX_TYPE_DGPS" }
  | { type: "GPS_FIX_TYPE_RTK_FLOAT" }
  | { type: "GPS_FIX_TYPE_RTK_FIXED" }
  | { type: "GPS_FIX_TYPE_STATIC" }
  | { type: "GPS_FIX_TYPE_PPP" };
