// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GripperActions =
  | { type: "GRIPPER_ACTION_RELEASE" }
  | { type: "GRIPPER_ACTION_GRAB" };
