// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HeadingType =
  | { type: "HEADING_TYPE_COURSE_OVER_GROUND" }
  | { type: "HEADING_TYPE_HEADING" };
