// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HERELINK_VIDEO_STREAM_INFORMATION_DATA {
  framerate: number;
  bitrate: number;
  resolution_h: number;
  resolution_v: number;
  rotation: number;
  camera_id: number;
  status: number;
  uri: Array<number>;
}
