// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpsFixType } from "./GpsFixType";
import type { MavLandedState } from "./MavLandedState";
import type { MavModeFlag } from "./MavModeFlag";

export interface HIGH_LATENCY_DATA {
  custom_mode: number;
  latitude: number;
  longitude: number;
  roll: number;
  pitch: number;
  heading: number;
  heading_sp: number;
  altitude_amsl: number;
  altitude_sp: number;
  wp_distance: number;
  base_mode: MavModeFlag;
  landed_state: MavLandedState;
  throttle: number;
  airspeed: number;
  airspeed_sp: number;
  groundspeed: number;
  climb_rate: number;
  gps_nsat: number;
  gps_fix_type: GpsFixType;
  battery_remaining: number;
  temperature: number;
  temperature_air: number;
  failsafe: number;
  wp_num: number;
}
