// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HIL_RC_INPUTS_RAW_DATA {
  time_usec: bigint;
  chan1_raw: number;
  chan2_raw: number;
  chan3_raw: number;
  chan4_raw: number;
  chan5_raw: number;
  chan6_raw: number;
  chan7_raw: number;
  chan8_raw: number;
  chan9_raw: number;
  chan10_raw: number;
  chan11_raw: number;
  chan12_raw: number;
  rssi: number;
}
