// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavModeFlag } from "./MavModeFlag";

export interface HIL_ACTUATOR_CONTROLS_DATA {
  time_usec: bigint;
  flags: bigint;
  controls: Array<number>;
  mode: MavModeFlag;
}
