// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavMode } from "./MavMode";

export interface HIL_CONTROLS_DATA {
  time_usec: bigint;
  roll_ailerons: number;
  pitch_elevator: number;
  yaw_rudder: number;
  throttle: number;
  aux1: number;
  aux2: number;
  aux3: number;
  aux4: number;
  mode: MavMode;
  nav_mode: number;
}
