// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HIL_GPS_DATA {
  time_usec: bigint;
  lat: number;
  lon: number;
  alt: number;
  eph: number;
  epv: number;
  vel: number;
  vn: number;
  ve: number;
  vd: number;
  cog: number;
  fix_type: number;
  satellites_visible: number;
}
