// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HIL_STATE_QUATERNION_DATA {
  time_usec: bigint;
  attitude_quaternion: Array<number>;
  rollspeed: number;
  pitchspeed: number;
  yawspeed: number;
  lat: number;
  lon: number;
  alt: number;
  vx: number;
  vy: number;
  vz: number;
  ind_airspeed: number;
  true_airspeed: number;
  xacc: number;
  yacc: number;
  zacc: number;
}
