// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HYGROMETER_SENSOR_DATA {
  temperature: number;
  humidity: number;
  id: number;
}
