// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IcarousTrackBandTypes } from "./IcarousTrackBandTypes";

export interface ICAROUS_KINEMATIC_BANDS_DATA {
  min1: number;
  max1: number;
  min2: number;
  max2: number;
  min3: number;
  max3: number;
  min4: number;
  max4: number;
  min5: number;
  max5: number;
  numBands: number;
  type1: IcarousTrackBandTypes;
  type2: IcarousTrackBandTypes;
  type3: IcarousTrackBandTypes;
  type4: IcarousTrackBandTypes;
  type5: IcarousTrackBandTypes;
}
