// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IcarousTrackBandTypes =
  | { type: "ICAROUS_TRACK_BAND_TYPE_NONE" }
  | { type: "ICAROUS_TRACK_BAND_TYPE_NEAR" }
  | { type: "ICAROUS_TRACK_BAND_TYPE_RECOVERY" };
