// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IcarousFmsState =
  | { type: "ICAROUS_FMS_STATE_IDLE" }
  | { type: "ICAROUS_FMS_STATE_TAKEOFF" }
  | { type: "ICAROUS_FMS_STATE_CLIMB" }
  | { type: "ICAROUS_FMS_STATE_CRUISE" }
  | { type: "ICAROUS_FMS_STATE_APPROACH" }
  | { type: "ICAROUS_FMS_STATE_LAND" };
