// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IcarousFmsState } from "./IcarousFmsState";

export interface ICAROUS_HEARTBEAT_DATA {
  status: IcarousFmsState;
}
