// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavFrame } from "./MavFrame";

export interface LANDING_TARGET_DATA {
  time_usec: bigint;
  angle_x: number;
  angle_y: number;
  distance: number;
  size_x: number;
  size_y: number;
  target_num: number;
  frame: MavFrame;
}
