// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LandingTargetType =
  | { type: "LANDING_TARGET_TYPE_LIGHT_BEACON" }
  | { type: "LANDING_TARGET_TYPE_RADIO_BEACON" }
  | { type: "LANDING_TARGET_TYPE_VISION_FIDUCIAL" }
  | { type: "LANDING_TARGET_TYPE_VISION_OTHER" };
