// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LED_CONTROL_DATA {
  target_system: number;
  target_component: number;
  instance: number;
  pattern: number;
  custom_len: number;
  custom_bytes: Array<number>;
}
