// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LedControlPattern =
  | { type: "LED_CONTROL_PATTERN_OFF" }
  | { type: "LED_CONTROL_PATTERN_FIRMWAREUPDATE" }
  | { type: "LED_CONTROL_PATTERN_CUSTOM" };
