// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitModule } from "./LimitModule";
import type { LimitsState } from "./LimitsState";

export interface LIMITS_STATUS_DATA {
  last_trigger: number;
  last_action: number;
  last_recovery: number;
  last_clear: number;
  breach_count: number;
  limits_state: LimitsState;
  mods_enabled: LimitModule;
  mods_required: LimitModule;
  mods_triggered: LimitModule;
}
