// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LimitsState =
  | { type: "LIMITS_INIT" }
  | { type: "LIMITS_DISABLED" }
  | { type: "LIMITS_ENABLED" }
  | { type: "LIMITS_TRIGGERED" }
  | { type: "LIMITS_RECOVERING" }
  | { type: "LIMITS_RECOVERED" };
