// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LINK_NODE_STATUS_DATA {
  timestamp: bigint;
  tx_rate: number;
  rx_rate: number;
  messages_sent: number;
  messages_received: number;
  messages_lost: number;
  rx_parse_err: number;
  tx_overflows: number;
  rx_overflows: number;
  tx_buf: number;
  rx_buf: number;
}
