// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavEstimatorType } from "./MavEstimatorType";

export interface LOCAL_POSITION_NED_COV_DATA {
  time_usec: bigint;
  x: number;
  y: number;
  z: number;
  vx: number;
  vy: number;
  vz: number;
  ax: number;
  ay: number;
  az: number;
  covariance: Array<number>;
  estimator_type: MavEstimatorType;
}
