// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LOG_DATA_DATA {
  ofs: number;
  id: number;
  count: number;
  data: Array<number>;
}
