// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LOG_REQUEST_DATA_DATA {
  ofs: number;
  count: number;
  id: number;
  target_system: number;
  target_component: number;
}
