// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LOG_ENTRY_DATA {
  time_utc: number;
  size: number;
  id: number;
  num_logs: number;
  last_log_num: number;
}
