// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LOGGING_DATA_DATA {
  sequence: number;
  target_system: number;
  target_component: number;
  length: number;
  first_message_offset: number;
  data: Array<number>;
}
