// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MagCalStatus } from "./MagCalStatus";

export interface MAG_CAL_PROGRESS_DATA {
  direction_x: number;
  direction_y: number;
  direction_z: number;
  compass_id: number;
  cal_mask: number;
  cal_status: MagCalStatus;
  attempt: number;
  completion_pct: number;
  completion_mask: Array<number>;
}
