// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MagCalStatus =
  | { type: "MAG_CAL_NOT_STARTED" }
  | { type: "MAG_CAL_WAITING_TO_START" }
  | { type: "MAG_CAL_RUNNING_STEP_ONE" }
  | { type: "MAG_CAL_RUNNING_STEP_TWO" }
  | { type: "MAG_CAL_SUCCESS" }
  | { type: "MAG_CAL_FAILED" }
  | { type: "MAG_CAL_BAD_ORIENTATION" }
  | { type: "MAG_CAL_BAD_RADIUS" };
