// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MANUAL_SETPOINT_DATA {
  time_boot_ms: number;
  roll: number;
  pitch: number;
  yaw: number;
  thrust: number;
  mode_switch: number;
  manual_override_switch: number;
}
