// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MANUAL_CONTROL_DATA {
  x: number;
  y: number;
  z: number;
  r: number;
  buttons: number;
  target: number;
}
