// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavAutopilot =
  | { type: "MAV_AUTOPILOT_GENERIC" }
  | { type: "MAV_AUTOPILOT_RESERVED" }
  | { type: "MAV_AUTOPILOT_SLUGS" }
  | { type: "MAV_AUTOPILOT_ARDUPILOTMEGA" }
  | { type: "MAV_AUTOPILOT_OPENPILOT" }
  | { type: "MAV_AUTOPILOT_GENERIC_WAYPOINTS_ONLY" }
  | { type: "MAV_AUTOPILOT_GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY" }
  | { type: "MAV_AUTOPILOT_GENERIC_MISSION_FULL" }
  | { type: "MAV_AUTOPILOT_INVALID" }
  | { type: "MAV_AUTOPILOT_PPZ" }
  | { type: "MAV_AUTOPILOT_UDB" }
  | { type: "MAV_AUTOPILOT_FP" }
  | { type: "MAV_AUTOPILOT_PX4" }
  | { type: "MAV_AUTOPILOT_SMACCMPILOT" }
  | { type: "MAV_AUTOPILOT_AUTOQUAD" }
  | { type: "MAV_AUTOPILOT_ARMAZILA" }
  | { type: "MAV_AUTOPILOT_AEROB" }
  | { type: "MAV_AUTOPILOT_ASLUAV" }
  | { type: "MAV_AUTOPILOT_SMARTAP" }
  | { type: "MAV_AUTOPILOT_AIRRAILS" }
  | { type: "MAV_AUTOPILOT_REFLEX" };
