// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavArmAuthDeniedReason =
  | { type: "MAV_ARM_AUTH_DENIED_REASON_GENERIC" }
  | { type: "MAV_ARM_AUTH_DENIED_REASON_NONE" }
  | { type: "MAV_ARM_AUTH_DENIED_REASON_INVALID_WAYPOINT" }
  | { type: "MAV_ARM_AUTH_DENIED_REASON_TIMEOUT" }
  | { type: "MAV_ARM_AUTH_DENIED_REASON_AIRSPACE_IN_USE" }
  | { type: "MAV_ARM_AUTH_DENIED_REASON_BAD_WEATHER" };
