// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavBatteryChargeState =
  | { type: "MAV_BATTERY_CHARGE_STATE_UNDEFINED" }
  | { type: "MAV_BATTERY_CHARGE_STATE_OK" }
  | { type: "MAV_BATTERY_CHARGE_STATE_LOW" }
  | { type: "MAV_BATTERY_CHARGE_STATE_CRITICAL" }
  | { type: "MAV_BATTERY_CHARGE_STATE_EMERGENCY" }
  | { type: "MAV_BATTERY_CHARGE_STATE_FAILED" }
  | { type: "MAV_BATTERY_CHARGE_STATE_UNHEALTHY" }
  | { type: "MAV_BATTERY_CHARGE_STATE_CHARGING" };
