// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavBatteryFunction =
  | { type: "MAV_BATTERY_FUNCTION_UNKNOWN" }
  | { type: "MAV_BATTERY_FUNCTION_ALL" }
  | { type: "MAV_BATTERY_FUNCTION_PROPULSION" }
  | { type: "MAV_BATTERY_FUNCTION_AVIONICS" }
  | { type: "MAV_BATTERY_FUNCTION_PAYLOAD" };
