// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavBatteryMode =
  | { type: "MAV_BATTERY_MODE_UNKNOWN" }
  | { type: "MAV_BATTERY_MODE_AUTO_DISCHARGING" }
  | { type: "MAV_BATTERY_MODE_HOT_SWAP" };
