// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavBatteryType =
  | { type: "MAV_BATTERY_TYPE_UNKNOWN" }
  | { type: "MAV_BATTERY_TYPE_LIPO" }
  | { type: "MAV_BATTERY_TYPE_LIFE" }
  | { type: "MAV_BATTERY_TYPE_LION" }
  | { type: "MAV_BATTERY_TYPE_NIMH" };
