// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavBatteryFault =
  | { type: "MAV_BATTERY_FAULT_DEEP_DISCHARGE" }
  | { type: "MAV_BATTERY_FAULT_SPIKES" }
  | { type: "MAV_BATTERY_FAULT_CELL_FAIL" }
  | { type: "MAV_BATTERY_FAULT_OVER_CURRENT" }
  | { type: "MAV_BATTERY_FAULT_OVER_TEMPERATURE" }
  | { type: "MAV_BATTERY_FAULT_UNDER_TEMPERATURE" }
  | { type: "MAV_BATTERY_FAULT_INCOMPATIBLE_VOLTAGE" }
  | { type: "MAV_BATTERY_FAULT_INCOMPATIBLE_FIRMWARE" }
  | { type: "BATTERY_FAULT_INCOMPATIBLE_CELLS_CONFIGURATION" };
