// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavCollisionThreatLevel =
  | { type: "MAV_COLLISION_THREAT_LEVEL_NONE" }
  | { type: "MAV_COLLISION_THREAT_LEVEL_LOW" }
  | { type: "MAV_COLLISION_THREAT_LEVEL_HIGH" };
