// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavCollisionSrc =
  | { type: "MAV_COLLISION_SRC_ADSB" }
  | { type: "MAV_COLLISION_SRC_MAVLINK_GPS_GLOBAL_INT" };
