// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavCollisionAction =
  | { type: "MAV_COLLISION_ACTION_NONE" }
  | { type: "MAV_COLLISION_ACTION_REPORT" }
  | { type: "MAV_COLLISION_ACTION_ASCEND_OR_DESCEND" }
  | { type: "MAV_COLLISION_ACTION_MOVE_HORIZONTALLY" }
  | { type: "MAV_COLLISION_ACTION_MOVE_PERPENDICULAR" }
  | { type: "MAV_COLLISION_ACTION_RTL" }
  | { type: "MAV_COLLISION_ACTION_HOVER" };
