// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavCmdAck =
  | { type: "MAV_CMD_ACK_OK" }
  | { type: "MAV_CMD_ACK_ERR_FAIL" }
  | { type: "MAV_CMD_ACK_ERR_ACCESS_DENIED" }
  | { type: "MAV_CMD_ACK_ERR_NOT_SUPPORTED" }
  | { type: "MAV_CMD_ACK_ERR_COORDINATE_FRAME_NOT_SUPPORTED" }
  | { type: "MAV_CMD_ACK_ERR_COORDINATES_OUT_OF_RANGE" }
  | { type: "MAV_CMD_ACK_ERR_X_LAT_OUT_OF_RANGE" }
  | { type: "MAV_CMD_ACK_ERR_Y_LON_OUT_OF_RANGE" }
  | { type: "MAV_CMD_ACK_ERR_Z_ALT_OUT_OF_RANGE" };
