// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavDistanceSensor =
  | { type: "MAV_DISTANCE_SENSOR_LASER" }
  | { type: "MAV_DISTANCE_SENSOR_ULTRASOUND" }
  | { type: "MAV_DISTANCE_SENSOR_INFRARED" }
  | { type: "MAV_DISTANCE_SENSOR_RADAR" }
  | { type: "MAV_DISTANCE_SENSOR_UNKNOWN" };
