// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavDataStream =
  | { type: "MAV_DATA_STREAM_ALL" }
  | { type: "MAV_DATA_STREAM_RAW_SENSORS" }
  | { type: "MAV_DATA_STREAM_EXTENDED_STATUS" }
  | { type: "MAV_DATA_STREAM_RC_CHANNELS" }
  | { type: "MAV_DATA_STREAM_RAW_CONTROLLER" }
  | { type: "MAV_DATA_STREAM_POSITION" }
  | { type: "MAV_DATA_STREAM_EXTRA1" }
  | { type: "MAV_DATA_STREAM_EXTRA2" }
  | { type: "MAV_DATA_STREAM_EXTRA3" };
