// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavEstimatorType =
  | { type: "MAV_ESTIMATOR_TYPE_UNKNOWN" }
  | { type: "MAV_ESTIMATOR_TYPE_NAIVE" }
  | { type: "MAV_ESTIMATOR_TYPE_VISION" }
  | { type: "MAV_ESTIMATOR_TYPE_VIO" }
  | { type: "MAV_ESTIMATOR_TYPE_GPS" }
  | { type: "MAV_ESTIMATOR_TYPE_GPS_INS" }
  | { type: "MAV_ESTIMATOR_TYPE_MOCAP" }
  | { type: "MAV_ESTIMATOR_TYPE_LIDAR" }
  | { type: "MAV_ESTIMATOR_TYPE_AUTOPILOT" };
