// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavFrame =
  | { type: "MAV_FRAME_GLOBAL" }
  | { type: "MAV_FRAME_LOCAL_NED" }
  | { type: "MAV_FRAME_MISSION" }
  | { type: "MAV_FRAME_GLOBAL_RELATIVE_ALT" }
  | { type: "MAV_FRAME_LOCAL_ENU" }
  | { type: "MAV_FRAME_GLOBAL_INT" }
  | { type: "MAV_FRAME_GLOBAL_RELATIVE_ALT_INT" }
  | { type: "MAV_FRAME_LOCAL_OFFSET_NED" }
  | { type: "MAV_FRAME_BODY_NED" }
  | { type: "MAV_FRAME_BODY_OFFSET_NED" }
  | { type: "MAV_FRAME_GLOBAL_TERRAIN_ALT" }
  | { type: "MAV_FRAME_GLOBAL_TERRAIN_ALT_INT" }
  | { type: "MAV_FRAME_BODY_FRD" }
  | { type: "MAV_FRAME_RESERVED_13" }
  | { type: "MAV_FRAME_RESERVED_14" }
  | { type: "MAV_FRAME_RESERVED_15" }
  | { type: "MAV_FRAME_RESERVED_16" }
  | { type: "MAV_FRAME_RESERVED_17" }
  | { type: "MAV_FRAME_RESERVED_18" }
  | { type: "MAV_FRAME_RESERVED_19" }
  | { type: "MAV_FRAME_LOCAL_FRD" }
  | { type: "MAV_FRAME_LOCAL_FLU" };
