// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavFtpOpcode =
  | { type: "MAV_FTP_OPCODE_NONE" }
  | { type: "MAV_FTP_OPCODE_TERMINATESESSION" }
  | { type: "MAV_FTP_OPCODE_RESETSESSION" }
  | { type: "MAV_FTP_OPCODE_LISTDIRECTORY" }
  | { type: "MAV_FTP_OPCODE_OPENFILERO" }
  | { type: "MAV_FTP_OPCODE_READFILE" }
  | { type: "MAV_FTP_OPCODE_CREATEFILE" }
  | { type: "MAV_FTP_OPCODE_WRITEFILE" }
  | { type: "MAV_FTP_OPCODE_REMOVEFILE" }
  | { type: "MAV_FTP_OPCODE_CREATEDIRECTORY" }
  | { type: "MAV_FTP_OPCODE_REMOVEDIRECTORY" }
  | { type: "MAV_FTP_OPCODE_OPENFILEWO" }
  | { type: "MAV_FTP_OPCODE_TRUNCATEFILE" }
  | { type: "MAV_FTP_OPCODE_RENAME" }
  | { type: "MAV_FTP_OPCODE_CALCFILECRC" }
  | { type: "MAV_FTP_OPCODE_BURSTREADFILE" }
  | { type: "MAV_FTP_OPCODE_ACK" }
  | { type: "MAV_FTP_OPCODE_NAK" };
