// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavFtpErr =
  | { type: "MAV_FTP_ERR_NONE" }
  | { type: "MAV_FTP_ERR_FAIL" }
  | { type: "MAV_FTP_ERR_FAILERRNO" }
  | { type: "MAV_FTP_ERR_INVALIDDATASIZE" }
  | { type: "MAV_FTP_ERR_INVALIDSESSION" }
  | { type: "MAV_FTP_ERR_NOSESSIONSAVAILABLE" }
  | { type: "MAV_FTP_ERR_EOF" }
  | { type: "MAV_FTP_ERR_UNKNOWNCOMMAND" }
  | { type: "MAV_FTP_ERR_FILEEXISTS" }
  | { type: "MAV_FTP_ERR_FILEPROTECTED" }
  | { type: "MAV_FTP_ERR_FILENOTFOUND" };
