// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavGoto =
  | { type: "MAV_GOTO_DO_HOLD" }
  | { type: "MAV_GOTO_DO_CONTINUE" }
  | { type: "MAV_GOTO_HOLD_AT_CURRENT_POSITION" }
  | { type: "MAV_GOTO_HOLD_AT_SPECIFIED_POSITION" };
