// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavlinkDataStreamType =
  | { type: "MAVLINK_DATA_STREAM_IMG_JPEG" }
  | { type: "MAVLINK_DATA_STREAM_IMG_BMP" }
  | { type: "MAVLINK_DATA_STREAM_IMG_RAW8U" }
  | { type: "MAVLINK_DATA_STREAM_IMG_RAW32U" }
  | { type: "MAVLINK_DATA_STREAM_IMG_PGM" }
  | { type: "MAVLINK_DATA_STREAM_IMG_PNG" };
