// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavLandedState =
  | { type: "MAV_LANDED_STATE_UNDEFINED" }
  | { type: "MAV_LANDED_STATE_ON_GROUND" }
  | { type: "MAV_LANDED_STATE_IN_AIR" }
  | { type: "MAV_LANDED_STATE_TAKEOFF" }
  | { type: "MAV_LANDED_STATE_LANDING" };
