// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavMountMode =
  | { type: "MAV_MOUNT_MODE_RETRACT" }
  | { type: "MAV_MOUNT_MODE_NEUTRAL" }
  | { type: "MAV_MOUNT_MODE_MAVLINK_TARGETING" }
  | { type: "MAV_MOUNT_MODE_RC_TARGETING" }
  | { type: "MAV_MOUNT_MODE_GPS_POINT" }
  | { type: "MAV_MOUNT_MODE_SYSID_TARGET" }
  | { type: "MAV_MOUNT_MODE_HOME_LOCATION" };
