// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavMode =
  | { type: "MAV_MODE_PREFLIGHT" }
  | { type: "MAV_MODE_STABILIZE_DISARMED" }
  | { type: "MAV_MODE_STABILIZE_ARMED" }
  | { type: "MAV_MODE_MANUAL_DISARMED" }
  | { type: "MAV_MODE_MANUAL_ARMED" }
  | { type: "MAV_MODE_GUIDED_DISARMED" }
  | { type: "MAV_MODE_GUIDED_ARMED" }
  | { type: "MAV_MODE_AUTO_DISARMED" }
  | { type: "MAV_MODE_AUTO_ARMED" }
  | { type: "MAV_MODE_TEST_DISARMED" }
  | { type: "MAV_MODE_TEST_ARMED" };
