// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavMissionType =
  | { type: "MAV_MISSION_TYPE_MISSION" }
  | { type: "MAV_MISSION_TYPE_FENCE" }
  | { type: "MAV_MISSION_TYPE_RALLY" }
  | { type: "MAV_MISSION_TYPE_ALL" };
