// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavMissionResult =
  | { type: "MAV_MISSION_ACCEPTED" }
  | { type: "MAV_MISSION_ERROR" }
  | { type: "MAV_MISSION_UNSUPPORTED_FRAME" }
  | { type: "MAV_MISSION_UNSUPPORTED" }
  | { type: "MAV_MISSION_NO_SPACE" }
  | { type: "MAV_MISSION_INVALID" }
  | { type: "MAV_MISSION_INVALID_PARAM1" }
  | { type: "MAV_MISSION_INVALID_PARAM2" }
  | { type: "MAV_MISSION_INVALID_PARAM3" }
  | { type: "MAV_MISSION_INVALID_PARAM4" }
  | { type: "MAV_MISSION_INVALID_PARAM5_X" }
  | { type: "MAV_MISSION_INVALID_PARAM6_Y" }
  | { type: "MAV_MISSION_INVALID_PARAM7" }
  | { type: "MAV_MISSION_INVALID_SEQUENCE" }
  | { type: "MAV_MISSION_DENIED" }
  | { type: "MAV_MISSION_OPERATION_CANCELLED" };
