// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavModeGimbal =
  | { type: "MAV_MODE_GIMBAL_UNINITIALIZED" }
  | { type: "MAV_MODE_GIMBAL_CALIBRATING_PITCH" }
  | { type: "MAV_MODE_GIMBAL_CALIBRATING_ROLL" }
  | { type: "MAV_MODE_GIMBAL_CALIBRATING_YAW" }
  | { type: "MAV_MODE_GIMBAL_INITIALIZED" }
  | { type: "MAV_MODE_GIMBAL_ACTIVE" }
  | { type: "MAV_MODE_GIMBAL_RATE_CMD_TIMEOUT" };
