// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavModeFlagDecodePosition =
  | { type: "MAV_MODE_FLAG_DECODE_POSITION_SAFETY" }
  | { type: "MAV_MODE_FLAG_DECODE_POSITION_MANUAL" }
  | { type: "MAV_MODE_FLAG_DECODE_POSITION_HIL" }
  | { type: "MAV_MODE_FLAG_DECODE_POSITION_STABILIZE" }
  | { type: "MAV_MODE_FLAG_DECODE_POSITION_GUIDED" }
  | { type: "MAV_MODE_FLAG_DECODE_POSITION_AUTO" }
  | { type: "MAV_MODE_FLAG_DECODE_POSITION_TEST" }
  | { type: "MAV_MODE_FLAG_DECODE_POSITION_CUSTOM_MODE" };
