// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidSpeedAcc =
  | { type: "MAV_ODID_SPEED_ACC_UNKNOWN" }
  | { type: "MAV_ODID_SPEED_ACC_10_METERS_PER_SECOND" }
  | { type: "MAV_ODID_SPEED_ACC_3_METERS_PER_SECOND" }
  | { type: "MAV_ODID_SPEED_ACC_1_METERS_PER_SECOND" }
  | { type: "MAV_ODID_SPEED_ACC_0_3_METERS_PER_SECOND" };
