// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidCategoryEu =
  | { type: "MAV_ODID_CATEGORY_EU_UNDECLARED" }
  | { type: "MAV_ODID_CATEGORY_EU_OPEN" }
  | { type: "MAV_ODID_CATEGORY_EU_SPECIFIC" }
  | { type: "MAV_ODID_CATEGORY_EU_CERTIFIED" };
