// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidDescType =
  | { type: "MAV_ODID_DESC_TYPE_TEXT" }
  | { type: "MAV_ODID_DESC_TYPE_EMERGENCY" }
  | { type: "MAV_ODID_DESC_TYPE_EXTENDED_STATUS" };
