// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidHorAcc =
  | { type: "MAV_ODID_HOR_ACC_UNKNOWN" }
  | { type: "MAV_ODID_HOR_ACC_10NM" }
  | { type: "MAV_ODID_HOR_ACC_4NM" }
  | { type: "MAV_ODID_HOR_ACC_2NM" }
  | { type: "MAV_ODID_HOR_ACC_1NM" }
  | { type: "MAV_ODID_HOR_ACC_0_5NM" }
  | { type: "MAV_ODID_HOR_ACC_0_3NM" }
  | { type: "MAV_ODID_HOR_ACC_0_1NM" }
  | { type: "MAV_ODID_HOR_ACC_0_05NM" }
  | { type: "MAV_ODID_HOR_ACC_30_METER" }
  | { type: "MAV_ODID_HOR_ACC_10_METER" }
  | { type: "MAV_ODID_HOR_ACC_3_METER" }
  | { type: "MAV_ODID_HOR_ACC_1_METER" };
