// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidClassEu =
  | { type: "MAV_ODID_CLASS_EU_UNDECLARED" }
  | { type: "MAV_ODID_CLASS_EU_CLASS_0" }
  | { type: "MAV_ODID_CLASS_EU_CLASS_1" }
  | { type: "MAV_ODID_CLASS_EU_CLASS_2" }
  | { type: "MAV_ODID_CLASS_EU_CLASS_3" }
  | { type: "MAV_ODID_CLASS_EU_CLASS_4" }
  | { type: "MAV_ODID_CLASS_EU_CLASS_5" }
  | { type: "MAV_ODID_CLASS_EU_CLASS_6" };
