// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidTimeAcc =
  | { type: "MAV_ODID_TIME_ACC_UNKNOWN" }
  | { type: "MAV_ODID_TIME_ACC_0_1_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_0_2_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_0_3_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_0_4_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_0_5_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_0_6_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_0_7_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_0_8_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_0_9_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_1_0_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_1_1_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_1_2_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_1_3_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_1_4_SECOND" }
  | { type: "MAV_ODID_TIME_ACC_1_5_SECOND" };
