// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidVerAcc =
  | { type: "MAV_ODID_VER_ACC_UNKNOWN" }
  | { type: "MAV_ODID_VER_ACC_150_METER" }
  | { type: "MAV_ODID_VER_ACC_45_METER" }
  | { type: "MAV_ODID_VER_ACC_25_METER" }
  | { type: "MAV_ODID_VER_ACC_10_METER" }
  | { type: "MAV_ODID_VER_ACC_3_METER" }
  | { type: "MAV_ODID_VER_ACC_1_METER" };
