// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidUaType =
  | { type: "MAV_ODID_UA_TYPE_NONE" }
  | { type: "MAV_ODID_UA_TYPE_AEROPLANE" }
  | { type: "MAV_ODID_UA_TYPE_HELICOPTER_OR_MULTIROTOR" }
  | { type: "MAV_ODID_UA_TYPE_GYROPLANE" }
  | { type: "MAV_ODID_UA_TYPE_HYBRID_LIFT" }
  | { type: "MAV_ODID_UA_TYPE_ORNITHOPTER" }
  | { type: "MAV_ODID_UA_TYPE_GLIDER" }
  | { type: "MAV_ODID_UA_TYPE_KITE" }
  | { type: "MAV_ODID_UA_TYPE_FREE_BALLOON" }
  | { type: "MAV_ODID_UA_TYPE_CAPTIVE_BALLOON" }
  | { type: "MAV_ODID_UA_TYPE_AIRSHIP" }
  | { type: "MAV_ODID_UA_TYPE_FREE_FALL_PARACHUTE" }
  | { type: "MAV_ODID_UA_TYPE_ROCKET" }
  | { type: "MAV_ODID_UA_TYPE_TETHERED_POWERED_AIRCRAFT" }
  | { type: "MAV_ODID_UA_TYPE_GROUND_OBSTACLE" }
  | { type: "MAV_ODID_UA_TYPE_OTHER" };
