// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidClassificationType =
  | { type: "MAV_ODID_CLASSIFICATION_TYPE_UNDECLARED" }
  | { type: "MAV_ODID_CLASSIFICATION_TYPE_EU" };
