// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidStatus =
  | { type: "MAV_ODID_STATUS_UNDECLARED" }
  | { type: "MAV_ODID_STATUS_GROUND" }
  | { type: "MAV_ODID_STATUS_AIRBORNE" }
  | { type: "MAV_ODID_STATUS_EMERGENCY" }
  | { type: "MAV_ODID_STATUS_REMOTE_ID_SYSTEM_FAILURE" };
