// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidAuthType =
  | { type: "MAV_ODID_AUTH_TYPE_NONE" }
  | { type: "MAV_ODID_AUTH_TYPE_UAS_ID_SIGNATURE" }
  | { type: "MAV_ODID_AUTH_TYPE_OPERATOR_ID_SIGNATURE" }
  | { type: "MAV_ODID_AUTH_TYPE_MESSAGE_SET_SIGNATURE" }
  | { type: "MAV_ODID_AUTH_TYPE_NETWORK_REMOTE_ID" }
  | { type: "MAV_ODID_AUTH_TYPE_SPECIFIC_AUTHENTICATION" };
