// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidIdType =
  | { type: "MAV_ODID_ID_TYPE_NONE" }
  | { type: "MAV_ODID_ID_TYPE_SERIAL_NUMBER" }
  | { type: "MAV_ODID_ID_TYPE_CAA_REGISTRATION_ID" }
  | { type: "MAV_ODID_ID_TYPE_UTM_ASSIGNED_UUID" }
  | { type: "MAV_ODID_ID_TYPE_SPECIFIC_SESSION_ID" };
