// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidHeightRef =
  | { type: "MAV_ODID_HEIGHT_REF_OVER_TAKEOFF" }
  | { type: "MAV_ODID_HEIGHT_REF_OVER_GROUND" };
