// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidArmStatus =
  | { type: "MAV_ODID_ARM_STATUS_GOOD_TO_ARM" }
  | { type: "MAV_ODID_ARM_STATUS_PRE_ARM_FAIL_GENERIC" };
