// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavOdidOperatorLocationType =
  | { type: "MAV_ODID_OPERATOR_LOCATION_TYPE_TAKEOFF" }
  | { type: "MAV_ODID_OPERATOR_LOCATION_TYPE_LIVE_GNSS" }
  | { type: "MAV_ODID_OPERATOR_LOCATION_TYPE_FIXED" };
