// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavParamExtType =
  | { type: "MAV_PARAM_EXT_TYPE_UINT8" }
  | { type: "MAV_PARAM_EXT_TYPE_INT8" }
  | { type: "MAV_PARAM_EXT_TYPE_UINT16" }
  | { type: "MAV_PARAM_EXT_TYPE_INT16" }
  | { type: "MAV_PARAM_EXT_TYPE_UINT32" }
  | { type: "MAV_PARAM_EXT_TYPE_INT32" }
  | { type: "MAV_PARAM_EXT_TYPE_UINT64" }
  | { type: "MAV_PARAM_EXT_TYPE_INT64" }
  | { type: "MAV_PARAM_EXT_TYPE_REAL32" }
  | { type: "MAV_PARAM_EXT_TYPE_REAL64" }
  | { type: "MAV_PARAM_EXT_TYPE_CUSTOM" };
