// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavRemoteLogDataBlockStatuses =
  | { type: "MAV_REMOTE_LOG_DATA_BLOCK_NACK" }
  | { type: "MAV_REMOTE_LOG_DATA_BLOCK_ACK" };
