// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavResult =
  | { type: "MAV_RESULT_ACCEPTED" }
  | { type: "MAV_RESULT_TEMPORARILY_REJECTED" }
  | { type: "MAV_RESULT_DENIED" }
  | { type: "MAV_RESULT_UNSUPPORTED" }
  | { type: "MAV_RESULT_FAILED" }
  | { type: "MAV_RESULT_IN_PROGRESS" }
  | { type: "MAV_RESULT_CANCELLED" };
