// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavRoi =
  | { type: "MAV_ROI_NONE" }
  | { type: "MAV_ROI_WPNEXT" }
  | { type: "MAV_ROI_WPINDEX" }
  | { type: "MAV_ROI_LOCATION" }
  | { type: "MAV_ROI_TARGET" };
