// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavState =
  | { type: "MAV_STATE_UNINIT" }
  | { type: "MAV_STATE_BOOT" }
  | { type: "MAV_STATE_CALIBRATING" }
  | { type: "MAV_STATE_STANDBY" }
  | { type: "MAV_STATE_ACTIVE" }
  | { type: "MAV_STATE_CRITICAL" }
  | { type: "MAV_STATE_EMERGENCY" }
  | { type: "MAV_STATE_POWEROFF" }
  | { type: "MAV_STATE_FLIGHT_TERMINATION" };
