// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavSeverity =
  | { type: "MAV_SEVERITY_EMERGENCY" }
  | { type: "MAV_SEVERITY_ALERT" }
  | { type: "MAV_SEVERITY_CRITICAL" }
  | { type: "MAV_SEVERITY_ERROR" }
  | { type: "MAV_SEVERITY_WARNING" }
  | { type: "MAV_SEVERITY_NOTICE" }
  | { type: "MAV_SEVERITY_INFO" }
  | { type: "MAV_SEVERITY_DEBUG" };
