// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MavVtolState =
  | { type: "MAV_VTOL_STATE_UNDEFINED" }
  | { type: "MAV_VTOL_STATE_TRANSITION_TO_FW" }
  | { type: "MAV_VTOL_STATE_TRANSITION_TO_MC" }
  | { type: "MAV_VTOL_STATE_MC" }
  | { type: "MAV_VTOL_STATE_FW" };
