// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MCU_STATUS_DATA {
  MCU_temperature: number;
  MCU_voltage: number;
  MCU_voltage_min: number;
  MCU_voltage_max: number;
  id: number;
}
