// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MEMORY_VECT_DATA {
  address: number;
  ver: number;
  mavtype: number;
  value: Array<number>;
}
