// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissionState =
  | { type: "MISSION_STATE_UNKNOWN" }
  | { type: "MISSION_STATE_NO_MISSION" }
  | { type: "MISSION_STATE_NOT_STARTED" }
  | { type: "MISSION_STATE_ACTIVE" }
  | { type: "MISSION_STATE_PAUSED" }
  | { type: "MISSION_STATE_COMPLETE" };
