// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MISSION_SET_CURRENT_DATA {
  seq: number;
  target_system: number;
  target_component: number;
}
