// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavMissionResult } from "./MavMissionResult";

export interface MISSION_ACK_DATA {
  target_system: number;
  target_component: number;
  mavtype: MavMissionResult;
}
