// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MISSION_WRITE_PARTIAL_LIST_DATA {
  start_index: number;
  end_index: number;
  target_system: number;
  target_component: number;
}
