// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MotorTestThrottleType =
  | { type: "MOTOR_TEST_THROTTLE_PERCENT" }
  | { type: "MOTOR_TEST_THROTTLE_PWM" }
  | { type: "MOTOR_TEST_THROTTLE_PILOT" }
  | { type: "MOTOR_TEST_COMPASS_CAL" };
