// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MotorTestOrder =
  | { type: "MOTOR_TEST_ORDER_DEFAULT" }
  | { type: "MOTOR_TEST_ORDER_SEQUENCE" }
  | { type: "MOTOR_TEST_ORDER_BOARD" };
