// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MOUNT_ORIENTATION_DATA {
  time_boot_ms: number;
  roll: number;
  pitch: number;
  yaw: number;
}
