// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MOUNT_STATUS_DATA {
  pointing_a: number;
  pointing_b: number;
  pointing_c: number;
  target_system: number;
  target_component: number;
}
