// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MOUNT_CONTROL_DATA {
  input_a: number;
  input_b: number;
  input_c: number;
  target_system: number;
  target_component: number;
  save_position: number;
}
