// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavMountMode } from "./MavMountMode";

export interface MOUNT_CONFIGURE_DATA {
  target_system: number;
  target_component: number;
  mount_mode: MavMountMode;
  stab_roll: number;
  stab_pitch: number;
  stab_yaw: number;
}
