// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NAMED_VALUE_INT_DATA {
  time_boot_ms: number;
  value: number;
  name: Array<number>;
}
