// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NAV_CONTROLLER_OUTPUT_DATA {
  nav_roll: number;
  nav_pitch: number;
  alt_error: number;
  aspd_error: number;
  xtrack_error: number;
  nav_bearing: number;
  target_bearing: number;
  wp_dist: number;
}
