// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NavVtolLandOptions =
  | { type: "NAV_VTOL_LAND_OPTIONS_DEFAULT" }
  | { type: "NAV_VTOL_LAND_OPTIONS_FW_DESCENT" }
  | { type: "NAV_VTOL_LAND_OPTIONS_HOVER_DESCENT" };
