// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavDistanceSensor } from "./MavDistanceSensor";

export interface OBSTACLE_DISTANCE_DATA {
  time_usec: bigint;
  distances: Array<number>;
  min_distance: number;
  max_distance: number;
  sensor_type: MavDistanceSensor;
  increment: number;
}
