// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavDistanceSensor } from "./MavDistanceSensor";
import type { MavFrame } from "./MavFrame";

export interface OBSTACLE_DISTANCE_3D_DATA {
  time_boot_ms: number;
  x: number;
  y: number;
  z: number;
  min_distance: number;
  max_distance: number;
  obstacle_id: number;
  sensor_type: MavDistanceSensor;
  frame: MavFrame;
}
