// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ONBOARD_COMPUTER_STATUS_DATA {
  time_usec: bigint;
  uptime: number;
  ram_usage: number;
  ram_total: number;
  storage_type: Array<number>;
  storage_usage: Array<number>;
  storage_total: Array<number>;
  link_type: Array<number>;
  link_tx_rate: Array<number>;
  link_rx_rate: Array<number>;
  link_tx_max: Array<number>;
  link_rx_max: Array<number>;
  fan_speed: Array<number>;
  mavtype: number;
  cpu_cores: Array<number>;
  cpu_combined: Array<number>;
  gpu_cores: Array<number>;
  gpu_combined: Array<number>;
  temperature_board: number;
  temperature_core: Array<number>;
}
