// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavOdidArmStatus } from "./MavOdidArmStatus";

export interface OPEN_DRONE_ID_ARM_STATUS_DATA {
  status: MavOdidArmStatus;
  error: Array<number>;
}
