// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavOdidIdType } from "./MavOdidIdType";
import type { MavOdidUaType } from "./MavOdidUaType";

export interface OPEN_DRONE_ID_BASIC_ID_DATA {
  target_system: number;
  target_component: number;
  id_or_mac: Array<number>;
  id_type: MavOdidIdType;
  ua_type: MavOdidUaType;
  uas_id: Array<number>;
}
