// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavOdidHeightRef } from "./MavOdidHeightRef";
import type { MavOdidHorAcc } from "./MavOdidHorAcc";
import type { MavOdidSpeedAcc } from "./MavOdidSpeedAcc";
import type { MavOdidStatus } from "./MavOdidStatus";
import type { MavOdidTimeAcc } from "./MavOdidTimeAcc";
import type { MavOdidVerAcc } from "./MavOdidVerAcc";

export interface OPEN_DRONE_ID_LOCATION_DATA {
  latitude: number;
  longitude: number;
  altitude_barometric: number;
  altitude_geodetic: number;
  height: number;
  timestamp: number;
  direction: number;
  speed_horizontal: number;
  speed_vertical: number;
  target_system: number;
  target_component: number;
  id_or_mac: Array<number>;
  status: MavOdidStatus;
  height_reference: MavOdidHeightRef;
  horizontal_accuracy: MavOdidHorAcc;
  vertical_accuracy: MavOdidVerAcc;
  barometer_accuracy: MavOdidVerAcc;
  speed_accuracy: MavOdidSpeedAcc;
  timestamp_accuracy: MavOdidTimeAcc;
}
