// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OPEN_DRONE_ID_SYSTEM_UPDATE_DATA {
  operator_latitude: number;
  operator_longitude: number;
  operator_altitude_geo: number;
  timestamp: number;
  target_system: number;
  target_component: number;
}
