// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavOdidOperatorIdType } from "./MavOdidOperatorIdType";

export interface OPEN_DRONE_ID_OPERATOR_ID_DATA {
  target_system: number;
  target_component: number;
  id_or_mac: Array<number>;
  operator_id_type: MavOdidOperatorIdType;
  operator_id: Array<number>;
}
