// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavOdidDescType } from "./MavOdidDescType";

export interface OPEN_DRONE_ID_SELF_ID_DATA {
  target_system: number;
  target_component: number;
  id_or_mac: Array<number>;
  description_type: MavOdidDescType;
  description: Array<number>;
}
