// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavOdidAuthType } from "./MavOdidAuthType";

export interface OPEN_DRONE_ID_AUTHENTICATION_DATA {
  timestamp: number;
  target_system: number;
  target_component: number;
  id_or_mac: Array<number>;
  authentication_type: MavOdidAuthType;
  data_page: number;
  last_page_index: number;
  length: number;
  authentication_data: Array<number>;
}
