// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OPTICAL_FLOW_DATA {
  time_usec: bigint;
  flow_comp_m_x: number;
  flow_comp_m_y: number;
  ground_distance: number;
  flow_x: number;
  flow_y: number;
  sensor_id: number;
  quality: number;
}
