// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OPTICAL_FLOW_RAD_DATA {
  time_usec: bigint;
  integration_time_us: number;
  integrated_x: number;
  integrated_y: number;
  integrated_xgyro: number;
  integrated_ygyro: number;
  integrated_zgyro: number;
  time_delta_distance_us: number;
  distance: number;
  temperature: number;
  sensor_id: number;
  quality: number;
}
