// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavFrame } from "./MavFrame";

export interface ORBIT_EXECUTION_STATUS_DATA {
  time_usec: bigint;
  radius: number;
  x: number;
  y: number;
  z: number;
  frame: MavFrame;
}
