// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrbitYawBehaviour =
  | { type: "ORBIT_YAW_BEHAVIOUR_HOLD_FRONT_TO_CIRCLE_CENTER" }
  | { type: "ORBIT_YAW_BEHAVIOUR_HOLD_INITIAL_HEADING" }
  | { type: "ORBIT_YAW_BEHAVIOUR_UNCONTROLLED" }
  | { type: "ORBIT_YAW_BEHAVIOUR_HOLD_FRONT_TANGENT_TO_CIRCLE" }
  | { type: "ORBIT_YAW_BEHAVIOUR_RC_CONTROLLED" };
