// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsdParamConfigError } from "./OsdParamConfigError";

export interface OSD_PARAM_CONFIG_REPLY_DATA {
  request_id: number;
  result: OsdParamConfigError;
}
