// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OSD_PARAM_SHOW_CONFIG_DATA {
  request_id: number;
  target_system: number;
  target_component: number;
  osd_screen: number;
  osd_index: number;
}
