// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsdParamConfigType } from "./OsdParamConfigType";

export interface OSD_PARAM_CONFIG_DATA {
  request_id: number;
  min_value: number;
  max_value: number;
  increment: number;
  target_system: number;
  target_component: number;
  osd_screen: number;
  osd_index: number;
  param_id: Array<number>;
  config_type: OsdParamConfigType;
}
