// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OsdParamConfigType =
  | { type: "OSD_PARAM_NONE" }
  | { type: "OSD_PARAM_SERIAL_PROTOCOL" }
  | { type: "OSD_PARAM_SERVO_FUNCTION" }
  | { type: "OSD_PARAM_AUX_FUNCTION" }
  | { type: "OSD_PARAM_FLIGHT_MODE" }
  | { type: "OSD_PARAM_FAILSAFE_ACTION" }
  | { type: "OSD_PARAM_FAILSAFE_ACTION_1" }
  | { type: "OSD_PARAM_FAILSAFE_ACTION_2" }
  | { type: "OSD_PARAM_NUM_TYPES" };
