// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OsdParamConfigError =
  | { type: "OSD_PARAM_SUCCESS" }
  | { type: "OSD_PARAM_INVALID_SCREEN" }
  | { type: "OSD_PARAM_INVALID_PARAMETER_INDEX" }
  | { type: "OSD_PARAM_INVALID_PARAMETER" };
