// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PARAM_EXT_REQUEST_READ_DATA {
  param_index: number;
  target_system: number;
  target_component: number;
  param_id: Array<number>;
}
