// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PARAM_MAP_RC_DATA {
  param_value0: number;
  scale: number;
  param_value_min: number;
  param_value_max: number;
  param_index: number;
  target_system: number;
  target_component: number;
  param_id: Array<number>;
  parameter_rc_channel_index: number;
}
