// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParachuteAction =
  | { type: "PARACHUTE_DISABLE" }
  | { type: "PARACHUTE_ENABLE" }
  | { type: "PARACHUTE_RELEASE" };
