// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavParamType } from "./MavParamType";

export interface PARAM_SET_DATA {
  param_value: number;
  target_system: number;
  target_component: number;
  param_id: Array<number>;
  param_type: MavParamType;
}
