// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavParamExtType } from "./MavParamExtType";

export interface PARAM_EXT_SET_DATA {
  target_system: number;
  target_component: number;
  param_id: Array<number>;
  param_value: Array<number>;
  param_type: MavParamExtType;
}
