// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavParamExtType } from "./MavParamExtType";

export interface PARAM_EXT_VALUE_DATA {
  param_count: number;
  param_index: number;
  param_id: Array<number>;
  param_value: Array<number>;
  param_type: MavParamExtType;
}
