// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavParamType } from "./MavParamType";

export interface PARAM_VALUE_DATA {
  param_value: number;
  param_count: number;
  param_index: number;
  param_id: Array<number>;
  param_type: MavParamType;
}
