// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParamAck =
  | { type: "PARAM_ACK_ACCEPTED" }
  | { type: "PARAM_ACK_VALUE_UNSUPPORTED" }
  | { type: "PARAM_ACK_FAILED" }
  | { type: "PARAM_ACK_IN_PROGRESS" };
