// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavParamExtType } from "./MavParamExtType";
import type { ParamAck } from "./ParamAck";

export interface PARAM_EXT_ACK_DATA {
  param_id: Array<number>;
  param_value: Array<number>;
  param_type: MavParamExtType;
  param_result: ParamAck;
}
