// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PidTuningAxis } from "./PidTuningAxis";

export interface PID_TUNING_DATA {
  desired: number;
  achieved: number;
  FF: number;
  P: number;
  I: number;
  D: number;
  axis: PidTuningAxis;
}
