// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PidTuningAxis =
  | { type: "PID_TUNING_ROLL" }
  | { type: "PID_TUNING_PITCH" }
  | { type: "PID_TUNING_YAW" }
  | { type: "PID_TUNING_ACCZ" }
  | { type: "PID_TUNING_STEER" }
  | { type: "PID_TUNING_LANDING" };
