// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PING_DATA {
  time_usec: bigint;
  seq: number;
  target_system: number;
  target_component: number;
}
