// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaneMode =
  | { type: "PLANE_MODE_MANUAL" }
  | { type: "PLANE_MODE_CIRCLE" }
  | { type: "PLANE_MODE_STABILIZE" }
  | { type: "PLANE_MODE_TRAINING" }
  | { type: "PLANE_MODE_ACRO" }
  | { type: "PLANE_MODE_FLY_BY_WIRE_A" }
  | { type: "PLANE_MODE_FLY_BY_WIRE_B" }
  | { type: "PLANE_MODE_CRUISE" }
  | { type: "PLANE_MODE_AUTOTUNE" }
  | { type: "PLANE_MODE_AUTO" }
  | { type: "PLANE_MODE_RTL" }
  | { type: "PLANE_MODE_LOITER" }
  | { type: "PLANE_MODE_TAKEOFF" }
  | { type: "PLANE_MODE_AVOID_ADSB" }
  | { type: "PLANE_MODE_GUIDED" }
  | { type: "PLANE_MODE_INITIALIZING" }
  | { type: "PLANE_MODE_QSTABILIZE" }
  | { type: "PLANE_MODE_QHOVER" }
  | { type: "PLANE_MODE_QLOITER" }
  | { type: "PLANE_MODE_QLAND" }
  | { type: "PLANE_MODE_QRTL" }
  | { type: "PLANE_MODE_QAUTOTUNE" }
  | { type: "PLANE_MODE_QACRO" }
  | { type: "PLANE_MODE_THERMAL" };
