// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PLAY_TUNE_DATA {
  target_system: number;
  target_component: number;
  tune: Array<number>;
}
