// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavPowerStatus } from "./MavPowerStatus";

export interface POWER_STATUS_DATA {
  Vcc: number;
  Vservo: number;
  flags: MavPowerStatus;
}
