// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrecisionLandMode =
  | { type: "PRECISION_LAND_MODE_DISABLED" }
  | { type: "PRECISION_LAND_MODE_OPPORTUNISTIC" }
  | { type: "PRECISION_LAND_MODE_REQUIRED" };
