// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreflightStorageParameterAction =
  | { type: "PARAM_READ_PERSISTENT" }
  | { type: "PARAM_WRITE_PERSISTENT" }
  | { type: "PARAM_RESET_CONFIG_DEFAULT" }
  | { type: "PARAM_RESET_SENSOR_DEFAULT" }
  | { type: "PARAM_RESET_ALL_DEFAULT" };
