// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreflightStorageMissionAction =
  | { type: "MISSION_READ_PERSISTENT" }
  | { type: "MISSION_WRITE_PERSISTENT" }
  | { type: "MISSION_RESET_DEFAULT" };
