// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PROTOCOL_VERSION_DATA {
  version: number;
  min_version: number;
  max_version: number;
  spec_version_hash: Array<number>;
  library_version_hash: Array<number>;
}
