// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RallyFlags } from "./RallyFlags";

export interface RALLY_POINT_DATA {
  lat: number;
  lng: number;
  alt: number;
  break_alt: number;
  land_dir: number;
  target_system: number;
  target_component: number;
  idx: number;
  count: number;
  flags: RallyFlags;
}
