// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RAW_PRESSURE_DATA {
  time_usec: bigint;
  press_abs: number;
  press_diff1: number;
  press_diff2: number;
  temperature: number;
}
