// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RC_CHANNELS_DATA {
  time_boot_ms: number;
  chan1_raw: number;
  chan2_raw: number;
  chan3_raw: number;
  chan4_raw: number;
  chan5_raw: number;
  chan6_raw: number;
  chan7_raw: number;
  chan8_raw: number;
  chan9_raw: number;
  chan10_raw: number;
  chan11_raw: number;
  chan12_raw: number;
  chan13_raw: number;
  chan14_raw: number;
  chan15_raw: number;
  chan16_raw: number;
  chan17_raw: number;
  chan18_raw: number;
  chancount: number;
  rssi: number;
}
