// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RC_CHANNELS_OVERRIDE_DATA {
  chan1_raw: number;
  chan2_raw: number;
  chan3_raw: number;
  chan4_raw: number;
  chan5_raw: number;
  chan6_raw: number;
  chan7_raw: number;
  chan8_raw: number;
  target_system: number;
  target_component: number;
}
