// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RC_CHANNELS_SCALED_DATA {
  time_boot_ms: number;
  chan1_scaled: number;
  chan2_scaled: number;
  chan3_scaled: number;
  chan4_scaled: number;
  chan5_scaled: number;
  chan6_scaled: number;
  chan7_scaled: number;
  chan8_scaled: number;
  port: number;
  rssi: number;
}
