// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavRemoteLogDataBlockStatuses } from "./MavRemoteLogDataBlockStatuses";

export interface REMOTE_LOG_BLOCK_STATUS_DATA {
  seqno: number;
  target_system: number;
  target_component: number;
  status: MavRemoteLogDataBlockStatuses;
}
