// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavRemoteLogDataBlockCommands } from "./MavRemoteLogDataBlockCommands";

export interface REMOTE_LOG_DATA_BLOCK_DATA {
  seqno: MavRemoteLogDataBlockCommands;
  target_system: number;
  target_component: number;
  data: Array<number>;
}
