// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface REQUEST_DATA_STREAM_DATA {
  req_message_rate: number;
  target_system: number;
  target_component: number;
  req_stream_id: number;
  start_stop: number;
}
