// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface REQUEST_EVENT_DATA {
  first_sequence: number;
  last_sequence: number;
  target_system: number;
  target_component: number;
}
