// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RESOURCE_REQUEST_DATA {
  request_id: number;
  uri_type: number;
  uri: Array<number>;
  transfer_type: number;
  storage: Array<number>;
}
