// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavEventErrorReason } from "./MavEventErrorReason";

export interface RESPONSE_EVENT_ERROR_DATA {
  sequence: number;
  sequence_oldest_available: number;
  target_system: number;
  target_component: number;
  reason: MavEventErrorReason;
}
