// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoverMode =
  | { type: "ROVER_MODE_MANUAL" }
  | { type: "ROVER_MODE_ACRO" }
  | { type: "ROVER_MODE_STEERING" }
  | { type: "ROVER_MODE_HOLD" }
  | { type: "ROVER_MODE_LOITER" }
  | { type: "ROVER_MODE_FOLLOW" }
  | { type: "ROVER_MODE_SIMPLE" }
  | { type: "ROVER_MODE_AUTO" }
  | { type: "ROVER_MODE_RTL" }
  | { type: "ROVER_MODE_SMART_RTL" }
  | { type: "ROVER_MODE_GUIDED" }
  | { type: "ROVER_MODE_INITIALIZING" };
