// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RtkBaselineCoordinateSystem =
  | { type: "RTK_BASELINE_COORDINATE_SYSTEM_ECEF" }
  | { type: "RTK_BASELINE_COORDINATE_SYSTEM_NED" };
