// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavFrame } from "./MavFrame";

export interface SAFETY_ALLOWED_AREA_DATA {
  p1x: number;
  p1y: number;
  p1z: number;
  p2x: number;
  p2y: number;
  p2z: number;
  frame: MavFrame;
}
