// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SCALED_PRESSURE_DATA {
  time_boot_ms: number;
  press_abs: number;
  press_diff: number;
  temperature: number;
}
