// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScriptingCmd =
  | { type: "SCRIPTING_CMD_REPL_START" }
  | { type: "SCRIPTING_CMD_REPL_STOP" }
  | { type: "SCRIPTING_CMD_STOP" }
  | { type: "SCRIPTING_CMD_STOP_AND_RESTART" };
