// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SENSOR_OFFSETS_DATA {
  mag_declination: number;
  raw_press: number;
  raw_temp: number;
  gyro_cal_x: number;
  gyro_cal_y: number;
  gyro_cal_z: number;
  accel_cal_x: number;
  accel_cal_y: number;
  accel_cal_z: number;
  mag_ofs_x: number;
  mag_ofs_y: number;
  mag_ofs_z: number;
}
