// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerialControlDev } from "./SerialControlDev";
import type { SerialControlFlag } from "./SerialControlFlag";

export interface SERIAL_CONTROL_DATA {
  baudrate: number;
  timeout: number;
  device: SerialControlDev;
  flags: SerialControlFlag;
  count: number;
  data: Array<number>;
}
