// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SerialControlDev =
  | { type: "SERIAL_CONTROL_DEV_TELEM1" }
  | { type: "SERIAL_CONTROL_DEV_TELEM2" }
  | { type: "SERIAL_CONTROL_DEV_GPS1" }
  | { type: "SERIAL_CONTROL_DEV_GPS2" }
  | { type: "SERIAL_CONTROL_DEV_SHELL" }
  | { type: "SERIAL_CONTROL_SERIAL0" }
  | { type: "SERIAL_CONTROL_SERIAL1" }
  | { type: "SERIAL_CONTROL_SERIAL2" }
  | { type: "SERIAL_CONTROL_SERIAL3" }
  | { type: "SERIAL_CONTROL_SERIAL4" }
  | { type: "SERIAL_CONTROL_SERIAL5" }
  | { type: "SERIAL_CONTROL_SERIAL6" }
  | { type: "SERIAL_CONTROL_SERIAL7" }
  | { type: "SERIAL_CONTROL_SERIAL8" }
  | { type: "SERIAL_CONTROL_SERIAL9" };
