// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SERVO_OUTPUT_RAW_DATA {
  time_usec: number;
  servo1_raw: number;
  servo2_raw: number;
  servo3_raw: number;
  servo4_raw: number;
  servo5_raw: number;
  servo6_raw: number;
  servo7_raw: number;
  servo8_raw: number;
  port: number;
}
