// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SET_HOME_POSITION_DATA {
  latitude: number;
  longitude: number;
  altitude: number;
  x: number;
  y: number;
  z: number;
  q: Array<number>;
  approach_x: number;
  approach_y: number;
  approach_z: number;
  target_system: number;
}
