// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavMode } from "./MavMode";

export interface SET_MODE_DATA {
  custom_mode: number;
  target_system: number;
  base_mode: MavMode;
}
