// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SET_MAG_OFFSETS_DATA {
  mag_ofs_x: number;
  mag_ofs_y: number;
  mag_ofs_z: number;
  target_system: number;
  target_component: number;
}
