// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SET_ACTUATOR_CONTROL_TARGET_DATA {
  time_usec: bigint;
  controls: Array<number>;
  group_mlx: number;
  target_system: number;
  target_component: number;
}
