// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetFocusType =
  | { type: "FOCUS_TYPE_STEP" }
  | { type: "FOCUS_TYPE_CONTINUOUS" }
  | { type: "FOCUS_TYPE_RANGE" }
  | { type: "FOCUS_TYPE_METERS" }
  | { type: "FOCUS_TYPE_AUTO" }
  | { type: "FOCUS_TYPE_AUTO_SINGLE" }
  | { type: "FOCUS_TYPE_AUTO_CONTINUOUS" };
