// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SETUP_SIGNING_DATA {
  initial_timestamp: bigint;
  target_system: number;
  target_component: number;
  secret_key: Array<number>;
}
