// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SIM_STATE_DATA {
  q1: number;
  q2: number;
  q3: number;
  q4: number;
  roll: number;
  pitch: number;
  yaw: number;
  xacc: number;
  yacc: number;
  zacc: number;
  xgyro: number;
  ygyro: number;
  zgyro: number;
  lat: number;
  lon: number;
  alt: number;
  std_dev_horz: number;
  std_dev_vert: number;
  vn: number;
  ve: number;
  vd: number;
}
