// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeedType =
  | { type: "SPEED_TYPE_AIRSPEED" }
  | { type: "SPEED_TYPE_GROUNDSPEED" };
