// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavSeverity } from "./MavSeverity";

export interface STATUSTEXT_DATA {
  severity: MavSeverity;
  text: Array<number>;
}
