// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageStatus } from "./StorageStatus";

export interface STORAGE_INFORMATION_DATA {
  time_boot_ms: number;
  total_capacity: number;
  used_capacity: number;
  available_capacity: number;
  read_speed: number;
  write_speed: number;
  storage_id: number;
  storage_count: number;
  status: StorageStatus;
}
