// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageUsageFlag =
  | { type: "STORAGE_USAGE_FLAG_SET" }
  | { type: "STORAGE_USAGE_FLAG_PHOTO" }
  | { type: "STORAGE_USAGE_FLAG_VIDEO" }
  | { type: "STORAGE_USAGE_FLAG_LOGS" };
