// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageStatus =
  | { type: "STORAGE_STATUS_EMPTY" }
  | { type: "STORAGE_STATUS_UNFORMATTED" }
  | { type: "STORAGE_STATUS_READY" }
  | { type: "STORAGE_STATUS_NOT_SUPPORTED" };
