// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageType =
  | { type: "STORAGE_TYPE_UNKNOWN" }
  | { type: "STORAGE_TYPE_USB_STICK" }
  | { type: "STORAGE_TYPE_SD" }
  | { type: "STORAGE_TYPE_MICROSD" }
  | { type: "STORAGE_TYPE_CF" }
  | { type: "STORAGE_TYPE_CFE" }
  | { type: "STORAGE_TYPE_XQD" }
  | { type: "STORAGE_TYPE_HD" }
  | { type: "STORAGE_TYPE_OTHER" };
