// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubMode =
  | { type: "SUB_MODE_STABILIZE" }
  | { type: "SUB_MODE_ACRO" }
  | { type: "SUB_MODE_ALT_HOLD" }
  | { type: "SUB_MODE_AUTO" }
  | { type: "SUB_MODE_GUIDED" }
  | { type: "SUB_MODE_CIRCLE" }
  | { type: "SUB_MODE_SURFACE" }
  | { type: "SUB_MODE_POSHOLD" }
  | { type: "SUB_MODE_MANUAL" };
