// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TuneFormat } from "./TuneFormat";

export interface SUPPORTED_TUNES_DATA {
  format: TuneFormat;
  target_system: number;
  target_component: number;
}
