// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavSysStatusSensor } from "./MavSysStatusSensor";

export interface SYS_STATUS_DATA {
  onboard_control_sensors_present: MavSysStatusSensor;
  onboard_control_sensors_enabled: MavSysStatusSensor;
  onboard_control_sensors_health: MavSysStatusSensor;
  load: number;
  voltage_battery: number;
  current_battery: number;
  drop_rate_comm: number;
  errors_comm: number;
  errors_count1: number;
  errors_count2: number;
  errors_count3: number;
  errors_count4: number;
  battery_remaining: number;
}
