// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TERRAIN_REPORT_DATA {
  lat: number;
  lon: number;
  terrain_height: number;
  current_height: number;
  spacing: number;
  pending: number;
  loaded: number;
}
