// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TERRAIN_DATA_DATA {
  lat: number;
  lon: number;
  grid_spacing: number;
  data: Array<number>;
  gridbit: number;
}
