// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TERRAIN_REQUEST_DATA {
  mask: bigint;
  lat: number;
  lon: number;
  grid_spacing: number;
}
