// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TIME_ESTIMATE_TO_TARGET_DATA {
  safe_return: number;
  land: number;
  mission_next_item: number;
  mission_end: number;
  commanded_action: number;
}
