// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackerMode =
  | { type: "TRACKER_MODE_MANUAL" }
  | { type: "TRACKER_MODE_STOP" }
  | { type: "TRACKER_MODE_SCAN" }
  | { type: "TRACKER_MODE_SERVO_TEST" }
  | { type: "TRACKER_MODE_AUTO" }
  | { type: "TRACKER_MODE_INITIALIZING" };
