// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavTunnelPayloadType } from "./MavTunnelPayloadType";

export interface TUNNEL_DATA {
  payload_type: MavTunnelPayloadType;
  target_system: number;
  target_component: number;
  payload_length: number;
  payload: Array<number>;
}
