// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UavcanNodeMode =
  | { type: "UAVCAN_NODE_MODE_OPERATIONAL" }
  | { type: "UAVCAN_NODE_MODE_INITIALIZATION" }
  | { type: "UAVCAN_NODE_MODE_MAINTENANCE" }
  | { type: "UAVCAN_NODE_MODE_SOFTWARE_UPDATE" }
  | { type: "UAVCAN_NODE_MODE_OFFLINE" };
