// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UAVCAN_NODE_INFO_DATA {
  time_usec: bigint;
  uptime_sec: number;
  sw_vcs_commit: number;
  name: Array<number>;
  hw_version_major: number;
  hw_version_minor: number;
  hw_unique_id: Array<number>;
  sw_version_major: number;
  sw_version_minor: number;
}
