// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UavcanNodeHealth } from "./UavcanNodeHealth";
import type { UavcanNodeMode } from "./UavcanNodeMode";

export interface UAVCAN_NODE_STATUS_DATA {
  time_usec: bigint;
  uptime_sec: number;
  vendor_specific_status_code: number;
  health: UavcanNodeHealth;
  mode: UavcanNodeMode;
  sub_mode: number;
}
