// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UavcanNodeHealth =
  | { type: "UAVCAN_NODE_HEALTH_OK" }
  | { type: "UAVCAN_NODE_HEALTH_WARNING" }
  | { type: "UAVCAN_NODE_HEALTH_ERROR" }
  | { type: "UAVCAN_NODE_HEALTH_CRITICAL" };
