// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UavionixAdsbOutCfgGpsOffsetLon =
  | { type: "UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LON_NO_DATA" }
  | { type: "UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LON_APPLIED_BY_SENSOR" };
