// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UavionixAdsbOutDynamicGpsFix =
  | { type: "UAVIONIX_ADSB_OUT_DYNAMIC_GPS_FIX_NONE_0" }
  | { type: "UAVIONIX_ADSB_OUT_DYNAMIC_GPS_FIX_NONE_1" }
  | { type: "UAVIONIX_ADSB_OUT_DYNAMIC_GPS_FIX_2D" }
  | { type: "UAVIONIX_ADSB_OUT_DYNAMIC_GPS_FIX_3D" }
  | { type: "UAVIONIX_ADSB_OUT_DYNAMIC_GPS_FIX_DGPS" }
  | { type: "UAVIONIX_ADSB_OUT_DYNAMIC_GPS_FIX_RTK" };
