// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UavionixAdsbRfHealth } from "./UavionixAdsbRfHealth";

export interface UAVIONIX_ADSB_TRANSCEIVER_HEALTH_REPORT_DATA {
  rfHealth: UavionixAdsbRfHealth;
}
