// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdsbEmitterType } from "./AdsbEmitterType";
import type { UavionixAdsbOutCfgAircraftSize } from "./UavionixAdsbOutCfgAircraftSize";
import type { UavionixAdsbOutCfgGpsOffsetLat } from "./UavionixAdsbOutCfgGpsOffsetLat";
import type { UavionixAdsbOutCfgGpsOffsetLon } from "./UavionixAdsbOutCfgGpsOffsetLon";
import type { UavionixAdsbOutRfSelect } from "./UavionixAdsbOutRfSelect";

export interface UAVIONIX_ADSB_OUT_CFG_DATA {
  ICAO: number;
  stallSpeed: number;
  callsign: Array<number>;
  emitterType: AdsbEmitterType;
  aircraftSize: UavionixAdsbOutCfgAircraftSize;
  gpsOffsetLat: UavionixAdsbOutCfgGpsOffsetLat;
  gpsOffsetLon: UavionixAdsbOutCfgGpsOffsetLon;
  rfSelect: UavionixAdsbOutRfSelect;
}
