// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UavionixAdsbEmergencyStatus } from "./UavionixAdsbEmergencyStatus";
import type { UavionixAdsbOutDynamicGpsFix } from "./UavionixAdsbOutDynamicGpsFix";
import type { UavionixAdsbOutDynamicState } from "./UavionixAdsbOutDynamicState";

export interface UAVIONIX_ADSB_OUT_DYNAMIC_DATA {
  utcTime: number;
  gpsLat: number;
  gpsLon: number;
  gpsAlt: number;
  baroAltMSL: number;
  accuracyHor: number;
  accuracyVert: number;
  accuracyVel: number;
  velVert: number;
  velNS: number;
  VelEW: number;
  state: UavionixAdsbOutDynamicState;
  squawk: number;
  gpsFix: UavionixAdsbOutDynamicGpsFix;
  numSats: number;
  emergencyStatus: UavionixAdsbEmergencyStatus;
}
