// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UavionixAdsbEmergencyStatus =
  | { type: "UAVIONIX_ADSB_OUT_NO_EMERGENCY" }
  | { type: "UAVIONIX_ADSB_OUT_GENERAL_EMERGENCY" }
  | { type: "UAVIONIX_ADSB_OUT_LIFEGUARD_EMERGENCY" }
  | { type: "UAVIONIX_ADSB_OUT_MINIMUM_FUEL_EMERGENCY" }
  | { type: "UAVIONIX_ADSB_OUT_NO_COMM_EMERGENCY" }
  | { type: "UAVIONIX_ADSB_OUT_UNLAWFUL_INTERFERANCE_EMERGENCY" }
  | { type: "UAVIONIX_ADSB_OUT_DOWNED_AIRCRAFT_EMERGENCY" }
  | { type: "UAVIONIX_ADSB_OUT_RESERVED" };
