// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UavionixAdsbOutCfgGpsOffsetLat =
  | { type: "UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_NO_DATA" }
  | { type: "UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_LEFT_2M" }
  | { type: "UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_LEFT_4M" }
  | { type: "UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_LEFT_6M" }
  | { type: "UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_RIGHT_0M" }
  | { type: "UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_RIGHT_2M" }
  | { type: "UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_RIGHT_4M" }
  | { type: "UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LAT_RIGHT_6M" };
