// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UtmDataAvailFlags } from "./UtmDataAvailFlags";
import type { UtmFlightState } from "./UtmFlightState";

export interface UTM_GLOBAL_POSITION_DATA {
  time: bigint;
  lat: number;
  lon: number;
  alt: number;
  relative_alt: number;
  next_lat: number;
  next_lon: number;
  next_alt: number;
  vx: number;
  vy: number;
  vz: number;
  h_acc: number;
  v_acc: number;
  vel_acc: number;
  update_rate: number;
  uas_id: Array<number>;
  flight_state: UtmFlightState;
  flags: UtmDataAvailFlags;
}
