// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UtmFlightState =
  | { type: "UTM_FLIGHT_STATE_UNKNOWN" }
  | { type: "UTM_FLIGHT_STATE_GROUND" }
  | { type: "UTM_FLIGHT_STATE_AIRBORNE" }
  | { type: "UTM_FLIGHT_STATE_EMERGENCY" }
  | { type: "UTM_FLIGHT_STATE_NOCTRL" };
