// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface V2_EXTENSION_DATA {
  message_type: number;
  target_network: number;
  target_system: number;
  target_component: number;
  payload: Array<number>;
}
