// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface VFR_HUD_DATA {
  airspeed: number;
  groundspeed: number;
  alt: number;
  climb: number;
  heading: number;
  throttle: number;
}
