// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface VIBRATION_DATA {
  time_usec: bigint;
  vibration_x: number;
  vibration_y: number;
  vibration_z: number;
  clipping_0: number;
  clipping_1: number;
  clipping_2: number;
}
