// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface VICON_POSITION_ESTIMATE_DATA {
  usec: bigint;
  x: number;
  y: number;
  z: number;
  roll: number;
  pitch: number;
  yaw: number;
}
