// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoStreamStatusFlags =
  | { type: "VIDEO_STREAM_STATUS_FLAGS_RUNNING" }
  | { type: "VIDEO_STREAM_STATUS_FLAGS_THERMAL" };
