// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoStreamType =
  | { type: "VIDEO_STREAM_TYPE_RTSP" }
  | { type: "VIDEO_STREAM_TYPE_RTPUDP" }
  | { type: "VIDEO_STREAM_TYPE_TCP_MPEG" }
  | { type: "VIDEO_STREAM_TYPE_MPEG_TS_H264" };
