// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoStreamStatusFlags } from "./VideoStreamStatusFlags";

export interface VIDEO_STREAM_STATUS_DATA {
  framerate: number;
  bitrate: number;
  flags: VideoStreamStatusFlags;
  resolution_h: number;
  resolution_v: number;
  rotation: number;
  hfov: number;
  stream_id: number;
}
