// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoStreamStatusFlags } from "./VideoStreamStatusFlags";
import type { VideoStreamType } from "./VideoStreamType";

export interface VIDEO_STREAM_INFORMATION_DATA {
  framerate: number;
  bitrate: number;
  flags: VideoStreamStatusFlags;
  resolution_h: number;
  resolution_v: number;
  rotation: number;
  hfov: number;
  stream_id: number;
  count: number;
  mavtype: VideoStreamType;
  name: Array<number>;
  uri: Array<number>;
}
