// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface VISION_POSITION_DELTA_DATA {
  time_usec: bigint;
  time_delta_usec: bigint;
  angle_delta: Array<number>;
  position_delta: Array<number>;
  confidence: number;
}
