// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VtolTransitionHeading =
  | { type: "VTOL_TRANSITION_HEADING_VEHICLE_DEFAULT" }
  | { type: "VTOL_TRANSITION_HEADING_NEXT_WAYPOINT" }
  | { type: "VTOL_TRANSITION_HEADING_TAKEOFF" }
  | { type: "VTOL_TRANSITION_HEADING_SPECIFIED" }
  | { type: "VTOL_TRANSITION_HEADING_ANY" };
