// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WATER_DEPTH_DATA {
  time_boot_ms: number;
  lat: number;
  lng: number;
  alt: number;
  roll: number;
  pitch: number;
  yaw: number;
  distance: number;
  temperature: number;
  id: number;
  healthy: number;
}
