// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WifiConfigApMode =
  | { type: "WIFI_CONFIG_AP_MODE_UNDEFINED" }
  | { type: "WIFI_CONFIG_AP_MODE_AP" }
  | { type: "WIFI_CONFIG_AP_MODE_STATION" }
  | { type: "WIFI_CONFIG_AP_MODE_DISABLED" };
