// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WIFI_CONFIG_AP_DATA {
  ssid: Array<number>;
  password: Array<number>;
}
