// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WifiConfigApResponse =
  | { type: "WIFI_CONFIG_AP_RESPONSE_UNDEFINED" }
  | { type: "WIFI_CONFIG_AP_RESPONSE_ACCEPTED" }
  | { type: "WIFI_CONFIG_AP_RESPONSE_REJECTED" }
  | { type: "WIFI_CONFIG_AP_RESPONSE_MODE_ERROR" }
  | { type: "WIFI_CONFIG_AP_RESPONSE_SSID_ERROR" }
  | { type: "WIFI_CONFIG_AP_RESPONSE_PASSWORD_ERROR" };
