// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MavWinchStatusFlag } from "./MavWinchStatusFlag";

export interface WINCH_STATUS_DATA {
  time_usec: bigint;
  line_length: number;
  speed: number;
  tension: number;
  voltage: number;
  current: number;
  status: MavWinchStatusFlag;
  temperature: number;
}
