// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WinchActions =
  | { type: "WINCH_RELAXED" }
  | { type: "WINCH_RELATIVE_LENGTH_CONTROL" }
  | { type: "WINCH_RATE_CONTROL" }
  | { type: "WINCH_LOCK" }
  | { type: "WINCH_DELIVER" }
  | { type: "WINCH_HOLD" }
  | { type: "WINCH_RETRACT" }
  | { type: "WINCH_LOAD_LINE" }
  | { type: "WINCH_ABANDON_LINE" }
  | { type: "WINCH_LOAD_PAYLOAD" };
