// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WIND_COV_DATA {
  time_usec: bigint;
  wind_x: number;
  wind_y: number;
  wind_z: number;
  var_horiz: number;
  var_vert: number;
  wind_alt: number;
  horiz_accuracy: number;
  vert_accuracy: number;
}
